"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class AdminUsersController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize AdminUsersController object."""
        super(AdminUsersController, self).__init__(config)

    def admin_users_assign(self,
                           token,
                           team_id,
                           user_id,
                           is_restricted=None,
                           is_ultra_restricted=None,
                           channel_ids=None):
        """Perform a POST request to /admin.users.assign.

        Add an Enterprise user to a workspace.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): The ID of the user to add to the workspace.
            is_restricted (bool, optional): True if user should be added to the
                workspace as a guest.
            is_ultra_restricted (bool, optional): True if user should be added to the
                workspace as a single-channel guest.
            channel_ids (str, optional): Comma separated values of channel IDs to add
                user in the new workspace.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.assign")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .form_param(Parameter()
                .key("is_restricted")
                .value(is_restricted))
            .form_param(Parameter()
                .key("is_ultra_restricted")
                .value(is_ultra_restricted))
            .form_param(Parameter()
                .key("channel_ids")
                .value(channel_ids))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_invite(self,
                           token,
                           team_id,
                           email,
                           channel_ids,
                           custom_message=None,
                           real_name=None,
                           resend=None,
                           is_restricted=None,
                           is_ultra_restricted=None,
                           guest_expiration_ts=None):
        """Perform a POST request to /admin.users.invite.

        Invite a user to a workspace.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            email (str): The email address of the person to invite.
            channel_ids (str): A comma-separated list of `channel_id`s for this user
                to join. At least one channel is required.
            custom_message (str, optional): An optional message to send to the user
                in the invite email.
            real_name (str, optional): Full name of the user.
            resend (bool, optional): Allow this invite to be resent in the future if
                a user has not signed up yet. (default: false)
            is_restricted (bool, optional): Is this user a multi-channel guest user?
                (default: false)
            is_ultra_restricted (bool, optional): Is this user a single channel guest
                user? (default: false)
            guest_expiration_ts (str, optional): Timestamp when guest account should
                be disabled. Only include this timestamp if you are inviting a guest
                user and you want their account to expire on a certain date.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.invite")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("email")
                .value(email)
                .is_required(True))
            .form_param(Parameter()
                .key("channel_ids")
                .value(channel_ids)
                .is_required(True))
            .form_param(Parameter()
                .key("custom_message")
                .value(custom_message))
            .form_param(Parameter()
                .key("real_name")
                .value(real_name))
            .form_param(Parameter()
                .key("resend")
                .value(resend))
            .form_param(Parameter()
                .key("is_restricted")
                .value(is_restricted))
            .form_param(Parameter()
                .key("is_ultra_restricted")
                .value(is_ultra_restricted))
            .form_param(Parameter()
                .key("guest_expiration_ts")
                .value(guest_expiration_ts))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_list(self,
                         token,
                         team_id,
                         cursor=None,
                         limit=None):
        """Perform a GET request to /admin.users.list.

        List users on a workspace

        Args:
            token (str): Authentication token. Requires scope: `admin.users:read`
            team_id (str): The ID (`T1234`) of the workspace.
            cursor (str, optional): Set `cursor` to `next_cursor` returned by the
                previous call to list items in the next page.
            limit (int, optional): Limit for how many users to be retrieved per page

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.list")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("cursor")
                .value(cursor))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_remove(self,
                           token,
                           team_id,
                           user_id):
        """Perform a POST request to /admin.users.remove.

        Remove a user from a workspace.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): The ID of the user to remove.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.remove")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_set_admin(self,
                              token,
                              team_id,
                              user_id):
        """Perform a POST request to /admin.users.setAdmin.

        Set an existing guest, regular user, or owner to be an admin user.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): The ID of the user to designate as an admin.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.setAdmin")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_set_expiration(self,
                                   token,
                                   team_id,
                                   user_id,
                                   expiration_ts):
        """Perform a POST request to /admin.users.setExpiration.

        Set an expiration for a guest user

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): The ID of the user to set an expiration for.
            expiration_ts (int): Timestamp when guest account should be disabled.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.setExpiration")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .form_param(Parameter()
                .key("expiration_ts")
                .value(expiration_ts)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_set_owner(self,
                              token,
                              team_id,
                              user_id):
        """Perform a POST request to /admin.users.setOwner.

        Set an existing guest, regular user, or admin user to be a workspace owner.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): Id of the user to promote to owner.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.setOwner")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_users_set_regular(self,
                                token,
                                team_id,
                                user_id):
        """Perform a POST request to /admin.users.setRegular.

        Set an existing guest user, admin user, or owner to be a regular user.

        Args:
            token (str): Authentication token. Requires scope: `admin.users:write`
            team_id (str): The ID (`T1234`) of the workspace.
            user_id (str): The ID of the user to designate as a regular user.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.users.setRegular")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
