"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class AdminConversationsEkmController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize AdminConversationsEkmController object."""
        super(AdminConversationsEkmController, self).__init__(config)

    def admin_conversations_ekm_list_original_connected_channel_info(self,
                                                                     token,
                                                                     channel_ids=None,
                                                                     team_ids=None,
                                                                     limit=None,
                                                                     cursor=None):
        """Perform a GET request to
        /admin.conversations.ekm.listOriginalConnectedChannelInfo.

        List all disconnected channels—i.e., channels that were once connected to
        other workspaces and then disconnected—and the corresponding original channel
        IDs for key revocation with EKM.

        Args:
            token (str): Authentication token. Requires scope:
                `admin.conversations:read`
            channel_ids (str, optional): A comma-separated list of channels to filter
                to.
            team_ids (str, optional): A comma-separated list of the workspaces to
                which the channels you would like returned belong.
            limit (int, optional): The maximum number of items to return. Must be
                between 1 - 1000 both inclusive.
            cursor (str, optional): Set `cursor` to `next_cursor` returned by the
                previous call to list items in the next page.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.conversations.ekm.listOriginalConnectedChannelInfo")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("channel_ids")
                .value(channel_ids))
            .query_param(Parameter()
                .key("team_ids")
                .value(team_ids))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .query_param(Parameter()
                .key("cursor")
                .value(cursor))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
