"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class AdminConversationsRestrictAccessController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize AdminConversationsRestrictAccessController object."""
        super(AdminConversationsRestrictAccessController, self).__init__(config)

    def admin_conversations_restrict_access_add_group(self,
                                                      token,
                                                      group_id,
                                                      channel_id,
                                                      team_id=None):
        """Perform a POST request to
        /admin.conversations.restrictAccess.addGroup.

        Add an allowlist of IDP groups for accessing a channel

        Args:
            token (str): Authentication token. Requires scope:
                `admin.conversations:write`
            group_id (str): The [IDP
                Group](https://slack.com/help/articles/115001435788-Connect-identity-p
                rovider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for
                the private channel.
            channel_id (str): The channel to link this group to.
            team_id (str, optional): The workspace where the channel exists. This
                argument is required for channels only tied to one workspace, and
                optional for channels that are shared across an organization.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.conversations.restrictAccess.addGroup")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("group_id")
                .value(group_id)
                .is_required(True))
            .form_param(Parameter()
                .key("channel_id")
                .value(channel_id)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_conversations_restrict_access_list_groups(self,
                                                        token,
                                                        channel_id,
                                                        team_id=None):
        """Perform a GET request to
        /admin.conversations.restrictAccess.listGroups.

        List all IDP Groups linked to a channel

        Args:
            token (str): Authentication token. Requires scope:
                `admin.conversations:read`
            channel_id (str): The request query parameter.
            team_id (str, optional): The workspace where the channel exists. This
                argument is required for channels only tied to one workspace, and
                optional for channels that are shared across an organization.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.conversations.restrictAccess.listGroups")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("channel_id")
                .value(channel_id)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("team_id")
                .value(team_id))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def admin_conversations_restrict_access_remove_group(self,
                                                         token,
                                                         team_id,
                                                         group_id,
                                                         channel_id):
        """Perform a POST request to
        /admin.conversations.restrictAccess.removeGroup.

        Remove a linked IDP group linked from a private channel

        Args:
            token (str): Authentication token. Requires scope:
                `admin.conversations:write`
            team_id (str): The workspace where the channel exists. This argument is
                required for channels only tied to one workspace, and optional for
                channels that are shared across an organization.
            group_id (str): The [IDP
                Group](https://slack.com/help/articles/115001435788-Connect-identity-p
                rovider-groups-to-your-Enterprise-Grid-org) ID to remove from the
                private channel.
            channel_id (str): The channel to remove the linked group from.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/admin.conversations.restrictAccess.removeGroup")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("team_id")
                .value(team_id)
                .is_required(True))
            .form_param(Parameter()
                .key("group_id")
                .value(group_id)
                .is_required(True))
            .form_param(Parameter()
                .key("channel_id")
                .value(channel_id)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
