"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.api_test_error_schema_exception import (
    ApiTestErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.api_test_success_schema import (
    ApiTestSuccessSchema,
)


class ApiController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize ApiController object."""
        super(ApiController, self).__init__(config)

    def api_test(self,
                 error=None,
                 foo=None):
        """Perform a GET request to /api.test.

        Checks API calling code.

        Args:
            error (str, optional): Error response to return
            foo (str, optional): example property to return

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Standard success
                response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/api.test")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("error")
                .value(error))
            .query_param(Parameter()
                .key("foo")
                .value(foo))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ApiTestSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Artificial error response",
                ApiTestErrorSchemaException),
        ).execute()
