"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.apps_permissions_scopes_list_error_schema_exception import (
    AppsPermissionsScopesListErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.api_permissions_scopes_list_success_schema import (
    ApiPermissionsScopesListSuccessSchema,
)


class AppsPermissionsScopesController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize AppsPermissionsScopesController object."""
        super(AppsPermissionsScopesController, self).__init__(config)

    def apps_permissions_scopes_list(self,
                                     token):
        """Perform a GET request to /apps.permissions.scopes.list.

        Returns list of scopes this app has on a team.

        Args:
            token (str): Authentication token. Requires scope: `none`

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical successful
                paginated response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/apps.permissions.scopes.list")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ApiPermissionsScopesListSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                AppsPermissionsScopesListErrorSchemaException),
        ).execute()
