"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.apps_uninstall_error_schema_exception import (
    AppsUninstallErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.apps_uninstall_schema import (
    AppsUninstallSchema,
)


class AppsController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize AppsController object."""
        super(AppsController, self).__init__(config)

    def apps_uninstall(self,
                       token=None,
                       client_id=None,
                       client_secret=None):
        """Perform a GET request to /apps.uninstall.

        Uninstalls your app from a workspace.

        Args:
            token (str, optional): Authentication token. Requires scope: `none`
            client_id (str, optional): Issued when you created your application.
            client_secret (str, optional): Issued when you created your application.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/apps.uninstall")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("client_id")
                .value(client_id))
            .query_param(Parameter()
                .key("client_secret")
                .value(client_secret))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(AppsUninstallSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                AppsUninstallErrorSchemaException),
        ).execute()
