"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.chat_delete_error_schema_exception import (
    ChatDeleteErrorSchemaException,
)
from slackwebapi.exceptions.chat_delete_scheduled_message_error_schema_exception import (  # noqa: E501
    ChatDeleteScheduledMessageErrorSchemaException,
)
from slackwebapi.exceptions.chat_get_permalink_error_schema_exception import (
    ChatGetPermalinkErrorSchemaException,
)
from slackwebapi.exceptions.chat_me_message_error_schema_exception import (
    ChatMeMessageErrorSchemaException,
)
from slackwebapi.exceptions.chat_post_ephemeral_error_schema_exception import (
    ChatPostEphemeralErrorSchemaException,
)
from slackwebapi.exceptions.chat_post_message_error_schema_exception import (
    ChatPostMessageErrorSchemaException,
)
from slackwebapi.exceptions.chat_schedule_message_error_schema_exception import (
    ChatScheduleMessageErrorSchemaException,
)
from slackwebapi.exceptions.chat_unfurl_error_schema_exception import (
    ChatUnfurlErrorSchemaException,
)
from slackwebapi.exceptions.chat_update_error_schema_exception import (
    ChatUpdateErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.chat_delete_scheduled_message_schema import (
    ChatDeleteScheduledMessageSchema,
)
from slackwebapi.models.chat_delete_success_schema import (
    ChatDeleteSuccessSchema,
)
from slackwebapi.models.chat_get_permalink_success_schema import (
    ChatGetPermalinkSuccessSchema,
)
from slackwebapi.models.chat_me_message_schema import (
    ChatMeMessageSchema,
)
from slackwebapi.models.chat_post_ephemeral_success_schema import (
    ChatPostEphemeralSuccessSchema,
)
from slackwebapi.models.chat_post_message_success_schema import (
    ChatPostMessageSuccessSchema,
)
from slackwebapi.models.chat_schedule_message_success_schema import (
    ChatScheduleMessageSuccessSchema,
)
from slackwebapi.models.chat_unfurl_success_schema import (
    ChatUnfurlSuccessSchema,
)
from slackwebapi.models.chat_update_success_schema import (
    ChatUpdateSuccessSchema,
)


class ChatController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize ChatController object."""
        super(ChatController, self).__init__(config)

    def chat_delete(self,
                    token=None,
                    ts=None,
                    channel=None,
                    as_user=None):
        """Perform a POST request to /chat.delete.

        Deletes a message.

        Args:
            token (str, optional): Authentication token. Requires scope: `chat:write`
            ts (float, optional): Timestamp of the message to be deleted.
            channel (str, optional): Channel containing the message to be deleted.
            as_user (bool, optional): Pass true to delete the message as the authed
                user with `chat:write:user` scope. [Bot users](/bot-users) in this
                context are considered authed users. If unused or false, the message
                will be deleted with `chat:write:bot` scope.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.delete")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("ts")
                .value(ts))
            .form_param(Parameter()
                .key("channel")
                .value(channel))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatDeleteSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ChatDeleteErrorSchemaException),
        ).execute()

    def chat_delete_scheduled_message(self,
                                      token,
                                      channel,
                                      scheduled_message_id,
                                      as_user=None):
        """Perform a POST request to /chat.deleteScheduledMessage.

        Deletes a pending scheduled message from the queue.

        Args:
            token (str): Authentication token. Requires scope: `chat:write`
            channel (str): The channel the scheduled_message is posting to
            scheduled_message_id (str): `scheduled_message_id` returned from call to
                chat.scheduleMessage
            as_user (bool, optional): Pass true to delete the message as the authed
                user with `chat:write:user` scope. [Bot users](/bot-users) in this
                context are considered authed users. If unused or false, the message
                will be deleted with `chat:write:bot` scope.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.deleteScheduledMessage")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("scheduled_message_id")
                .value(scheduled_message_id)
                .is_required(True))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatDeleteScheduledMessageSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response if no message is found",
                ChatDeleteScheduledMessageErrorSchemaException),
        ).execute()

    def chat_get_permalink(self,
                           token,
                           channel,
                           message_ts):
        """Perform a GET request to /chat.getPermalink.

        Retrieve a permalink URL for a specific extant message

        Args:
            token (str): Authentication token. Requires scope: `none`
            channel (str): The ID of the conversation or channel containing the
                message
            message_ts (str): A message's `ts` value, uniquely identifying it within
                a channel

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Standard success
                response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.getPermalink")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .query_param(Parameter()
                .key("message_ts")
                .value(message_ts)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatGetPermalinkSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Error response when channel cannot be found",
                ChatGetPermalinkErrorSchemaException),
        ).execute()

    def chat_me_message(self,
                        token=None,
                        channel=None,
                        text=None):
        """Perform a POST request to /chat.meMessage.

        Share a me message into a channel.

        Args:
            token (str, optional): Authentication token. Requires scope: `chat:write`
            channel (str, optional): Channel to send message to. Can be a public
                channel, private group or IM channel. Can be an encoded ID, or a name.
            text (str, optional): Text of the message to send.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.meMessage")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("channel")
                .value(channel))
            .form_param(Parameter()
                .key("text")
                .value(text))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatMeMessageSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ChatMeMessageErrorSchemaException),
        ).execute()

    def chat_post_ephemeral(self,
                            token,
                            channel,
                            user,
                            as_user=None,
                            attachments=None,
                            blocks=None,
                            icon_emoji=None,
                            icon_url=None,
                            link_names=None,
                            parse=None,
                            text=None,
                            thread_ts=None,
                            username=None):
        """Perform a POST request to /chat.postEphemeral.

        Sends an ephemeral message to a user in a channel.

        Args:
            token (str): Authentication token. Requires scope: `chat:write`
            channel (str): Channel, private group, or IM channel to send message to.
                Can be an encoded ID, or a name.
            user (str): `id` of the user who will receive the ephemeral message. The
                user should be in the channel specified by the `channel` argument.
            as_user (bool, optional): Pass true to post the message as the authed
                user. Defaults to true if the chat:write:bot scope is not included.
                Otherwise, defaults to false.
            attachments (str, optional): A JSON-based array of structured
                attachments, presented as a URL-encoded string.
            blocks (str, optional): A JSON-based array of structured blocks,
                presented as a URL-encoded string.
            icon_emoji (str, optional): Emoji to use as the icon for this message.
                Overrides `icon_url`. Must be used in conjunction with `as_user` set
                to `false`, otherwise ignored. See [authorship](#authorship) below.
            icon_url (str, optional): URL to an image to use as the icon for this
                message. Must be used in conjunction with `as_user` set to false,
                otherwise ignored. See [authorship](#authorship) below.
            link_names (bool, optional): Find and link channel names and usernames.
            parse (str, optional): Change how messages are treated. Defaults to
                `none`. See [below](#formatting).
            text (str, optional): How this field works and whether it is required
                depends on other fields you use in your API call. [See
                below](#text_usage) for more detail.
            thread_ts (str, optional): Provide another message's `ts` value to post
                this message in a thread. Avoid using a reply's `ts` value; use its
                parent's value instead. Ephemeral messages in threads are only shown
                if there is already an active thread.
            username (str, optional): Set your bot's user name. Must be used in
                conjunction with `as_user` set to false, otherwise ignored. See
                [authorship](#authorship) below.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.postEphemeral")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("user")
                .value(user)
                .is_required(True))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .form_param(Parameter()
                .key("attachments")
                .value(attachments))
            .form_param(Parameter()
                .key("blocks")
                .value(blocks))
            .form_param(Parameter()
                .key("icon_emoji")
                .value(icon_emoji))
            .form_param(Parameter()
                .key("icon_url")
                .value(icon_url))
            .form_param(Parameter()
                .key("link_names")
                .value(link_names))
            .form_param(Parameter()
                .key("parse")
                .value(parse))
            .form_param(Parameter()
                .key("text")
                .value(text))
            .form_param(Parameter()
                .key("thread_ts")
                .value(thread_ts))
            .form_param(Parameter()
                .key("username")
                .value(username))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatPostEphemeralSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ChatPostEphemeralErrorSchemaException),
        ).execute()

    def chat_post_message(self,
                          token,
                          channel,
                          as_user=None,
                          attachments=None,
                          blocks=None,
                          icon_emoji=None,
                          icon_url=None,
                          link_names=None,
                          mrkdwn=None,
                          parse=None,
                          reply_broadcast=None,
                          text=None,
                          thread_ts=None,
                          unfurl_links=None,
                          unfurl_media=None,
                          username=None):
        """Perform a POST request to /chat.postMessage.

        Sends a message to a channel.

        Args:
            token (str): Authentication token. Requires scope: `chat:write`
            channel (str): Channel, private group, or IM channel to send message to.
                Can be an encoded ID, or a name. See [below](#channels) for more
                details.
            as_user (str, optional): Pass true to post the message as the authed
                user, instead of as a bot. Defaults to false. See
                [authorship](#authorship) below.
            attachments (str, optional): A JSON-based array of structured
                attachments, presented as a URL-encoded string.
            blocks (str, optional): A JSON-based array of structured blocks,
                presented as a URL-encoded string.
            icon_emoji (str, optional): Emoji to use as the icon for this message.
                Overrides `icon_url`. Must be used in conjunction with `as_user` set
                to `false`, otherwise ignored. See [authorship](#authorship) below.
            icon_url (str, optional): URL to an image to use as the icon for this
                message. Must be used in conjunction with `as_user` set to false,
                otherwise ignored. See [authorship](#authorship) below.
            link_names (bool, optional): Find and link channel names and usernames.
            mrkdwn (bool, optional): Disable Slack markup parsing by setting to
                `false`. Enabled by default.
            parse (str, optional): Change how messages are treated. Defaults to
                `none`. See [below](#formatting).
            reply_broadcast (bool, optional): Used in conjunction with `thread_ts`
                and indicates whether reply should be made visible to everyone in the
                channel or conversation. Defaults to `false`.
            text (str, optional): How this field works and whether it is required
                depends on other fields you use in your API call. [See
                below](#text_usage) for more detail.
            thread_ts (str, optional): Provide another message's `ts` value to make
                this message a reply. Avoid using a reply's `ts` value; use its
                parent instead.
            unfurl_links (bool, optional): Pass true to enable unfurling of primarily
                text-based content.
            unfurl_media (bool, optional): Pass false to disable unfurling of media
                content.
            username (str, optional): Set your bot's user name. Must be used in
                conjunction with `as_user` set to false, otherwise ignored. See
                [authorship](#authorship) below.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.postMessage")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .form_param(Parameter()
                .key("attachments")
                .value(attachments))
            .form_param(Parameter()
                .key("blocks")
                .value(blocks))
            .form_param(Parameter()
                .key("icon_emoji")
                .value(icon_emoji))
            .form_param(Parameter()
                .key("icon_url")
                .value(icon_url))
            .form_param(Parameter()
                .key("link_names")
                .value(link_names))
            .form_param(Parameter()
                .key("mrkdwn")
                .value(mrkdwn))
            .form_param(Parameter()
                .key("parse")
                .value(parse))
            .form_param(Parameter()
                .key("reply_broadcast")
                .value(reply_broadcast))
            .form_param(Parameter()
                .key("text")
                .value(text))
            .form_param(Parameter()
                .key("thread_ts")
                .value(thread_ts))
            .form_param(Parameter()
                .key("unfurl_links")
                .value(unfurl_links))
            .form_param(Parameter()
                .key("unfurl_media")
                .value(unfurl_media))
            .form_param(Parameter()
                .key("username")
                .value(username))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatPostMessageSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response if too many attachments are included",
                ChatPostMessageErrorSchemaException),
        ).execute()

    def chat_schedule_message(self,
                              token=None,
                              channel=None,
                              text=None,
                              post_at=None,
                              parse=None,
                              as_user=None,
                              link_names=None,
                              attachments=None,
                              blocks=None,
                              unfurl_links=None,
                              unfurl_media=None,
                              thread_ts=None,
                              reply_broadcast=None):
        """Perform a POST request to /chat.scheduleMessage.

        Schedules a message to be sent to a channel.

        Args:
            token (str, optional): Authentication token. Requires scope: `chat:write`
            channel (str, optional): Channel, private group, or DM channel to send
                message to. Can be an encoded ID, or a name. See [below](#channels)
                for more details.
            text (str, optional): How this field works and whether it is required
                depends on other fields you use in your API call. [See
                below](#text_usage) for more detail.
            post_at (str, optional): Unix EPOCH timestamp of time in future to send
                the message.
            parse (str, optional): Change how messages are treated. Defaults to
                `none`. See [chat.postMessage](chat.postMessage#formatting).
            as_user (bool, optional): Pass true to post the message as the authed
                user, instead of as a bot. Defaults to false. See
                [chat.postMessage](chat.postMessage#authorship).
            link_names (bool, optional): Find and link channel names and usernames.
            attachments (str, optional): A JSON-based array of structured
                attachments, presented as a URL-encoded string.
            blocks (str, optional): A JSON-based array of structured blocks,
                presented as a URL-encoded string.
            unfurl_links (bool, optional): Pass true to enable unfurling of primarily
                text-based content.
            unfurl_media (bool, optional): Pass false to disable unfurling of media
                content.
            thread_ts (float, optional): Provide another message's `ts` value to make
                this message a reply. Avoid using a reply's `ts` value; use its
                parent instead.
            reply_broadcast (bool, optional): Used in conjunction with `thread_ts`
                and indicates whether reply should be made visible to everyone in the
                channel or conversation. Defaults to `false`.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.scheduleMessage")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("channel")
                .value(channel))
            .form_param(Parameter()
                .key("text")
                .value(text))
            .form_param(Parameter()
                .key("post_at")
                .value(post_at))
            .form_param(Parameter()
                .key("parse")
                .value(parse))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .form_param(Parameter()
                .key("link_names")
                .value(link_names))
            .form_param(Parameter()
                .key("attachments")
                .value(attachments))
            .form_param(Parameter()
                .key("blocks")
                .value(blocks))
            .form_param(Parameter()
                .key("unfurl_links")
                .value(unfurl_links))
            .form_param(Parameter()
                .key("unfurl_media")
                .value(unfurl_media))
            .form_param(Parameter()
                .key("thread_ts")
                .value(thread_ts))
            .form_param(Parameter()
                .key("reply_broadcast")
                .value(reply_broadcast))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatScheduleMessageSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response if the `post_at` is invalid (ex. in the past "
                "or too far into the future)",
                ChatScheduleMessageErrorSchemaException),
        ).execute()

    def chat_unfurl(self,
                    token,
                    channel,
                    ts,
                    unfurls=None,
                    user_auth_message=None,
                    user_auth_required=None,
                    user_auth_url=None):
        """Perform a POST request to /chat.unfurl.

        Provide custom unfurl behavior for user-posted URLs

        Args:
            token (str): Authentication token. Requires scope: `links:write`
            channel (str): Channel ID of the message
            ts (str): Timestamp of the message to add unfurl behavior to.
            unfurls (str, optional): URL-encoded JSON map with keys set to URLs
                featured in the the message, pointing to their unfurl blocks or
                message attachments.
            user_auth_message (str, optional): Provide a simply-formatted string to
                send as an ephemeral message to the user as invitation to
                authenticate further and enable full unfurling behavior
            user_auth_required (bool, optional): Set to `true` or `1` to indicate the
                user must install your Slack app to trigger unfurls for this domain
            user_auth_url (str, optional): Send users to this custom URL where they
                will complete authentication in your app to fully trigger unfurling.
                Value should be properly URL-encoded.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical, minimal
                success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.unfurl")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("ts")
                .value(ts)
                .is_required(True))
            .form_param(Parameter()
                .key("unfurls")
                .value(unfurls))
            .form_param(Parameter()
                .key("user_auth_message")
                .value(user_auth_message))
            .form_param(Parameter()
                .key("user_auth_required")
                .value(user_auth_required))
            .form_param(Parameter()
                .key("user_auth_url")
                .value(user_auth_url))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatUnfurlSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ChatUnfurlErrorSchemaException),
        ).execute()

    def chat_update(self,
                    token,
                    channel,
                    ts,
                    as_user=None,
                    attachments=None,
                    blocks=None,
                    link_names=None,
                    parse=None,
                    text=None):
        """Perform a POST request to /chat.update.

        Updates a message.

        Args:
            token (str): Authentication token. Requires scope: `chat:write`
            channel (str): Channel containing the message to be updated.
            ts (str): Timestamp of the message to be updated.
            as_user (str, optional): Pass true to update the message as the authed
                user. [Bot users](/bot-users) in this context are considered authed
                users.
            attachments (str, optional): A JSON-based array of structured
                attachments, presented as a URL-encoded string. This field is
                required when not presenting `text`. If you don't include this field,
                the message's previous `attachments` will be retained. To remove
                previous `attachments`, include an empty array for this field.
            blocks (str, optional): A JSON-based array of [structured
                blocks](/block-kit/building), presented as a URL-encoded string. If
                you don't include this field, the message's previous `blocks` will be
                retained. To remove previous `blocks`, include an empty array for
                this field.
            link_names (str, optional): Find and link channel names and usernames.
                Defaults to `none`. If you do not specify a value for this field, the
                original value set for the message will be overwritten with the
                default, `none`.
            parse (str, optional): Change how messages are treated. Defaults to
                `client`, unlike `chat.postMessage`. Accepts either `none` or `full`.
                If you do not specify a value for this field, the original value set
                for the message will be overwritten with the default, `client`.
            text (str, optional): New text for the message, using the [default
                formatting rules](/reference/surfaces/formatting). It's not required
                when presenting `blocks` or `attachments`.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.update")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("ts")
                .value(ts)
                .is_required(True))
            .form_param(Parameter()
                .key("as_user")
                .value(as_user))
            .form_param(Parameter()
                .key("attachments")
                .value(attachments))
            .form_param(Parameter()
                .key("blocks")
                .value(blocks))
            .form_param(Parameter()
                .key("link_names")
                .value(link_names))
            .form_param(Parameter()
                .key("parse")
                .value(parse))
            .form_param(Parameter()
                .key("text")
                .value(text))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatUpdateSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ChatUpdateErrorSchemaException),
        ).execute()
