"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.chat_scheduled_messages_list_error_schema_exception import (
    ChatScheduledMessagesListErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.chat_scheduled_messages_list_schema import (
    ChatScheduledMessagesListSchema,
)


class ChatScheduledMessagesController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize ChatScheduledMessagesController object."""
        super(ChatScheduledMessagesController, self).__init__(config)

    def chat_scheduled_messages_list(self,
                                     token=None,
                                     channel=None,
                                     latest=None,
                                     oldest=None,
                                     limit=None,
                                     cursor=None):
        """Perform a GET request to /chat.scheduledMessages.list.

        Returns a list of scheduled messages.

        Args:
            token (str, optional): Authentication token. Requires scope: `none`
            channel (str, optional): The channel of the scheduled messages
            latest (float, optional): A UNIX timestamp of the latest value in the
                time range
            oldest (float, optional): A UNIX timestamp of the oldest value in the
                time range
            limit (int, optional): Maximum number of original entries to return.
            cursor (str, optional): For pagination purposes, this is the `cursor`
                value returned from a previous call to `chat.scheduledmessages.list`
                indicating where you want to start this call from.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/chat.scheduledMessages.list")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("channel")
                .value(channel))
            .query_param(Parameter()
                .key("latest")
                .value(latest))
            .query_param(Parameter()
                .key("oldest")
                .value(oldest))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .query_param(Parameter()
                .key("cursor")
                .value(cursor))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ChatScheduledMessagesListSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response if the channel passed is invalid",
                ChatScheduledMessagesListErrorSchemaException),
        ).execute()
