"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.dialog_open_error_schema_exception import (
    DialogOpenErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.dialog_open_schema import (
    DialogOpenSchema,
)


class DialogController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize DialogController object."""
        super(DialogController, self).__init__(config)

    def dialog_open(self,
                    token,
                    dialog,
                    trigger_id):
        """Perform a GET request to /dialog.open.

        Open a dialog with a user

        Args:
            token (str): Authentication token. Requires scope: `none`
            dialog (str): The dialog definition. This must be a JSON-encoded string.
            trigger_id (str): Exchange a trigger to post to the user.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response is quite minimal.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dialog.open")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("dialog")
                .value(dialog)
                .is_required(True))
            .query_param(Parameter()
                .key("trigger_id")
                .value(trigger_id)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DialogOpenSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response, before getting to any possible validation er"
                "rors.",
                DialogOpenErrorSchemaException),
        ).execute()
