"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.exceptions.dnd_end_dnd_error_schema_exception import (
    DndEndDndErrorSchemaException,
)
from slackwebapi.exceptions.dnd_end_snooze_error_schema_exception import (
    DndEndSnoozeErrorSchemaException,
)
from slackwebapi.exceptions.dnd_info_error_schema_exception import (
    DndInfoErrorSchemaException,
)
from slackwebapi.exceptions.dnd_set_snooze_error_schema_exception import (
    DndSetSnoozeErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)
from slackwebapi.models.dnd_end_dnd_schema import (
    DndEndDndSchema,
)
from slackwebapi.models.dnd_end_snooze_schema import (
    DndEndSnoozeSchema,
)
from slackwebapi.models.dnd_info_schema import (
    DndInfoSchema,
)
from slackwebapi.models.dnd_set_snooze_schema import (
    DndSetSnoozeSchema,
)


class DndController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize DndController object."""
        super(DndController, self).__init__(config)

    def dnd_end_dnd(self,
                    token):
        """Perform a POST request to /dnd.endDnd.

        Ends the current user's Do Not Disturb session immediately.

        Args:
            token (str): Authentication token. Requires scope: `dnd:write`

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dnd.endDnd")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DndEndDndSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DndEndDndErrorSchemaException),
        ).execute()

    def dnd_end_snooze(self,
                       token):
        """Perform a POST request to /dnd.endSnooze.

        Ends the current user's snooze mode immediately.

        Args:
            token (str): Authentication token. Requires scope: `dnd:write`

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dnd.endSnooze")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DndEndSnoozeSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DndEndSnoozeErrorSchemaException),
        ).execute()

    def dnd_info(self,
                 token=None,
                 user=None):
        """Perform a GET request to /dnd.info.

        Retrieves a user's current Do Not Disturb status.

        Args:
            token (str, optional): Authentication token. Requires scope: `dnd:read`
            user (str, optional): User to fetch status for (defaults to current user)

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dnd.info")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("user")
                .value(user))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DndInfoSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DndInfoErrorSchemaException),
        ).execute()

    def dnd_set_snooze(self,
                       token,
                       num_minutes):
        """Perform a POST request to /dnd.setSnooze.

        Turns on Do Not Disturb mode for the current user, or changes its duration.

        Args:
            token (str): Authentication token. Requires scope: `dnd:write`
            num_minutes (str): Number of minutes, from now, to snooze until.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dnd.setSnooze")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("num_minutes")
                .value(num_minutes)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DndSetSnoozeSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DndSetSnoozeErrorSchemaException),
        ).execute()

    def dnd_team_info(self,
                      token=None,
                      users=None):
        """Perform a GET request to /dnd.teamInfo.

        Retrieves the Do Not Disturb status for up to 50 users on a team.

        Args:
            token (str, optional): Authentication token. Requires scope: `dnd:read`
            users (str, optional): Comma-separated list of users to fetch Do Not
                Disturb status for

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/dnd.teamInfo")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("users")
                .value(users))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
