"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class FilesRemoteController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize FilesRemoteController object."""
        super(FilesRemoteController, self).__init__(config)

    def files_remote_add(self,
                         token=None,
                         external_id=None,
                         title=None,
                         filetype=None,
                         external_url=None,
                         preview_image=None,
                         indexable_file_contents=None):
        """Perform a POST request to /files.remote.add.

        Adds a file from a remote service

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:write`
            external_id (str, optional): Creator defined GUID for the file.
            title (str, optional): Title of the file being shared.
            filetype (str, optional): type of file
            external_url (str, optional): URL of the remote file.
            preview_image (str, optional): Preview of the document via
                `multipart/form-data`.
            indexable_file_contents (str, optional): A text file (txt, pdf, doc,
                etc.) containing textual search terms that are used to improve
                discovery of the remote file.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.add")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("external_id")
                .value(external_id))
            .form_param(Parameter()
                .key("title")
                .value(title))
            .form_param(Parameter()
                .key("filetype")
                .value(filetype))
            .form_param(Parameter()
                .key("external_url")
                .value(external_url))
            .form_param(Parameter()
                .key("preview_image")
                .value(preview_image))
            .form_param(Parameter()
                .key("indexable_file_contents")
                .value(indexable_file_contents))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def files_remote_info(self,
                          token=None,
                          file=None,
                          external_id=None):
        """Perform a GET request to /files.remote.info.

        Retrieve information about a remote file added to Slack

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:read`
            file (str, optional): Specify a file by providing its ID.
            external_id (str, optional): Creator defined GUID for the file.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.info")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("file")
                .value(file))
            .query_param(Parameter()
                .key("external_id")
                .value(external_id))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def files_remote_list(self,
                          token=None,
                          channel=None,
                          ts_from=None,
                          ts_to=None,
                          limit=None,
                          cursor=None):
        """Perform a GET request to /files.remote.list.

        Retrieve information about a remote file added to Slack

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:read`
            channel (str, optional): Filter files appearing in a specific channel,
                indicated by its ID.
            ts_from (float, optional): Filter files created after this timestamp
                (inclusive).
            ts_to (float, optional): Filter files created before this timestamp
                (inclusive).
            limit (int, optional): The maximum number of items to return.
            cursor (str, optional): Paginate through collections of data by setting
                the `cursor` parameter to a `next_cursor` attribute returned by a
                previous request's `response_metadata`. Default value fetches the
                first "page" of the collection. See [pagination](/docs/pagination)
                for more detail.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.list")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("channel")
                .value(channel))
            .query_param(Parameter()
                .key("ts_from")
                .value(ts_from))
            .query_param(Parameter()
                .key("ts_to")
                .value(ts_to))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .query_param(Parameter()
                .key("cursor")
                .value(cursor))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def files_remote_remove(self,
                            token=None,
                            file=None,
                            external_id=None):
        """Perform a POST request to /files.remote.remove.

        Remove a remote file.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:write`
            file (str, optional): Specify a file by providing its ID.
            external_id (str, optional): Creator defined GUID for the file.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.remove")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("file")
                .value(file))
            .form_param(Parameter()
                .key("external_id")
                .value(external_id))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def files_remote_share(self,
                           token=None,
                           file=None,
                           external_id=None,
                           channels=None):
        """Perform a GET request to /files.remote.share.

        Share a remote file into a channel.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:share`
            file (str, optional): Specify a file registered with Slack by providing
                its ID. Either this field or `external_id` or both are required.
            external_id (str, optional): The globally unique identifier (GUID) for
                the file, as set by the app registering the file with Slack.  Either
                this field or `file` or both are required.
            channels (str, optional): Comma-separated list of channel IDs where the
                file will be shared.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.share")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("file")
                .value(file))
            .query_param(Parameter()
                .key("external_id")
                .value(external_id))
            .query_param(Parameter()
                .key("channels")
                .value(channels))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def files_remote_update(self,
                            token=None,
                            file=None,
                            external_id=None,
                            title=None,
                            filetype=None,
                            external_url=None,
                            preview_image=None,
                            indexable_file_contents=None):
        """Perform a POST request to /files.remote.update.

        Updates an existing remote file.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `remote_files:write`
            file (str, optional): Specify a file by providing its ID.
            external_id (str, optional): Creator defined GUID for the file.
            title (str, optional): Title of the file being shared.
            filetype (str, optional): type of file
            external_url (str, optional): URL of the remote file.
            preview_image (str, optional): Preview of the document via
                `multipart/form-data`.
            indexable_file_contents (str, optional): File containing contents that
                can be used to improve searchability for the remote file.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/files.remote.update")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("file")
                .value(file))
            .form_param(Parameter()
                .key("external_id")
                .value(external_id))
            .form_param(Parameter()
                .key("title")
                .value(title))
            .form_param(Parameter()
                .key("filetype")
                .value(filetype))
            .form_param(Parameter()
                .key("external_url")
                .value(external_url))
            .form_param(Parameter()
                .key("preview_image")
                .value(preview_image))
            .form_param(Parameter()
                .key("indexable_file_contents")
                .value(indexable_file_contents))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
