"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.migration_exchange_error_schema_exception import (
    MigrationExchangeErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.migration_exchange_success_schema import (
    MigrationExchangeSuccessSchema,
)


class MigrationController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize MigrationController object."""
        super(MigrationController, self).__init__(config)

    def migration_exchange(self,
                           token,
                           users,
                           team_id=None,
                           to_old=None):
        """Perform a GET request to /migration.exchange.

        For Enterprise Grid workspaces, map local user IDs to global user IDs

        Args:
            token (str): Authentication token. Requires scope: `tokens.basic`
            users (str): A comma-separated list of user ids, up to 400 per request
            team_id (str, optional): Specify team_id starts with `T` in case of Org
                Token
            to_old (bool, optional): Specify `true` to convert `W` global user IDs to
                workspace-specific `U` IDs. Defaults to `false`.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response when mappings exist for the specified user IDs

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/migration.exchange")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("users")
                .value(users)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("team_id")
                .value(team_id))
            .query_param(Parameter()
                .key("to_old")
                .value(to_old))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(MigrationExchangeSuccessSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response when there are no mappings to provide",
                MigrationExchangeErrorSchemaException),
        ).execute()
