"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class OauthController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize OauthController object."""
        super(OauthController, self).__init__(config)

    def oauth_access(self,
                     client_id=None,
                     client_secret=None,
                     code=None,
                     redirect_uri=None,
                     single_channel=None):
        """Perform a GET request to /oauth.access.

        Exchanges a temporary OAuth verifier code for an access token.

        Args:
            client_id (str, optional): Issued when you created your application.
            client_secret (str, optional): Issued when you created your application.
            code (str, optional): The `code` param returned via the OAuth callback.
            redirect_uri (str, optional): This must match the originally submitted
                URI (if one was sent).
            single_channel (bool, optional): Request the user to add your app only to
                a single channel. Only valid with a [legacy workspace
                app](https://api.slack.com/legacy-workspace-apps).

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful user token
                negotiation for a single scope

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/oauth.access")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("client_id")
                .value(client_id))
            .query_param(Parameter()
                .key("client_secret")
                .value(client_secret))
            .query_param(Parameter()
                .key("code")
                .value(code))
            .query_param(Parameter()
                .key("redirect_uri")
                .value(redirect_uri))
            .query_param(Parameter()
                .key("single_channel")
                .value(single_channel))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()

    def oauth_token(self,
                    client_id=None,
                    client_secret=None,
                    code=None,
                    redirect_uri=None,
                    single_channel=None):
        """Perform a GET request to /oauth.token.

        Exchanges a temporary OAuth verifier code for a workspace token.

        Args:
            client_id (str, optional): Issued when you created your application.
            client_secret (str, optional): Issued when you created your application.
            code (str, optional): The `code` param returned via the OAuth callback.
            redirect_uri (str, optional): This must match the originally submitted
                URI (if one was sent).
            single_channel (bool, optional): Request the user to add your app only to
                a single channel.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Success example using a
                workspace app produces a very different kind of response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/oauth.token")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("client_id")
                .value(client_id))
            .query_param(Parameter()
                .key("client_secret")
                .value(client_secret))
            .query_param(Parameter()
                .key("code")
                .value(code))
            .query_param(Parameter()
                .key("redirect_uri")
                .value(redirect_uri))
            .query_param(Parameter()
                .key("single_channel")
                .value(single_channel))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
