"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.reactions_add_error_schema_exception import (
    ReactionsAddErrorSchemaException,
)
from slackwebapi.exceptions.reactions_get_error_schema_exception import (
    ReactionsGetErrorSchemaException,
)
from slackwebapi.exceptions.reactions_list_error_schema_exception import (
    ReactionsListErrorSchemaException,
)
from slackwebapi.exceptions.reactions_remove_error_schema_exception import (
    ReactionsRemoveErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.reactions_add_schema import (
    ReactionsAddSchema,
)
from slackwebapi.models.reactions_list_schema import (
    ReactionsListSchema,
)
from slackwebapi.models.reactions_remove_schema import (
    ReactionsRemoveSchema,
)


class ReactionsController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize ReactionsController object."""
        super(ReactionsController, self).__init__(config)

    def reactions_add(self,
                      channel,
                      name,
                      timestamp,
                      token):
        """Perform a POST request to /reactions.add.

        Adds a reaction to an item.

        Args:
            channel (str): Channel where the message to add reaction to was posted.
            name (str): Reaction (emoji) name.
            timestamp (str): Timestamp of the message to add reaction to.
            token (str): Authentication token. Requires scope: `reactions:write`

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reactions.add")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("channel")
                .value(channel)
                .is_required(True))
            .form_param(Parameter()
                .key("name")
                .value(name)
                .is_required(True))
            .form_param(Parameter()
                .key("timestamp")
                .value(timestamp)
                .is_required(True))
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ReactionsAddSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ReactionsAddErrorSchemaException),
        ).execute()

    def reactions_get(self,
                      token,
                      channel=None,
                      file=None,
                      file_comment=None,
                      full=None,
                      timestamp=None):
        """Perform a GET request to /reactions.get.

        Gets reactions for an item.

        Args:
            token (str): Authentication token. Requires scope: `reactions:read`
            channel (str, optional): Channel where the message to get reactions for
                was posted.
            file (str, optional): File to get reactions for.
            file_comment (str, optional): File comment to get reactions for.
            full (bool, optional): If true always return the complete reaction list.
            timestamp (str, optional): Timestamp of the message to get reactions for.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reactions.get")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("channel")
                .value(channel))
            .query_param(Parameter()
                .key("file")
                .value(file))
            .query_param(Parameter()
                .key("file_comment")
                .value(file_comment))
            .query_param(Parameter()
                .key("full")
                .value(full))
            .query_param(Parameter()
                .key("timestamp")
                .value(timestamp))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ReactionsGetErrorSchemaException),
        ).execute()

    def reactions_list(self,
                       token,
                       user=None,
                       full=None,
                       count=None,
                       page=None,
                       cursor=None,
                       limit=None):
        """Perform a GET request to /reactions.list.

        Lists reactions made by a user.

        Args:
            token (str): Authentication token. Requires scope: `reactions:read`
            user (str, optional): Show reactions made by this user. Defaults to the
                authed user.
            full (bool, optional): If true always return the complete reaction list.
            count (int, optional): The request query parameter.
            page (int, optional): The request query parameter.
            cursor (str, optional): Parameter for pagination. Set `cursor` equal to
                the `next_cursor` attribute returned by the previous request's
                `response_metadata`. This parameter is optional, but pagination is
                mandatory: the default value simply fetches the first "page" of the
                collection. See [pagination](/docs/pagination) for more details.
            limit (int, optional): The maximum number of items to return. Fewer than
                the requested number of items may be returned, even if the end of the
                list hasn't been reached.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reactions.list")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("user")
                .value(user))
            .query_param(Parameter()
                .key("full")
                .value(full))
            .query_param(Parameter()
                .key("count")
                .value(count))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("cursor")
                .value(cursor))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ReactionsListSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ReactionsListErrorSchemaException),
        ).execute()

    def reactions_remove(self,
                         token,
                         name,
                         file=None,
                         file_comment=None,
                         channel=None,
                         timestamp=None):
        """Perform a POST request to /reactions.remove.

        Removes a reaction from an item.

        Args:
            token (str): Authentication token. Requires scope: `reactions:write`
            name (str): Reaction (emoji) name.
            file (str, optional): File to remove reaction from.
            file_comment (str, optional): File comment to remove reaction from.
            channel (str, optional): Channel where the message to remove reaction
                from was posted.
            timestamp (str, optional): Timestamp of the message to remove reaction
                from.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reactions.remove")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("name")
                .value(name)
                .is_required(True))
            .form_param(Parameter()
                .key("file")
                .value(file))
            .form_param(Parameter()
                .key("file_comment")
                .value(file_comment))
            .form_param(Parameter()
                .key("channel")
                .value(channel))
            .form_param(Parameter()
                .key("timestamp")
                .value(timestamp))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ReactionsRemoveSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                ReactionsRemoveErrorSchemaException),
        ).execute()
