"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.reminders_add_error_schema_exception import (
    RemindersAddErrorSchemaException,
)
from slackwebapi.exceptions.reminders_complete_error_schema_exception import (
    RemindersCompleteErrorSchemaException,
)
from slackwebapi.exceptions.reminders_delete_error_schema_exception import (
    RemindersDeleteErrorSchemaException,
)
from slackwebapi.exceptions.reminders_info_error_schema_exception import (
    RemindersInfoErrorSchemaException,
)
from slackwebapi.exceptions.reminders_list_error_schema_exception import (
    RemindersListErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.reminders_add_schema import (
    RemindersAddSchema,
)
from slackwebapi.models.reminders_complete_schema import (
    RemindersCompleteSchema,
)
from slackwebapi.models.reminders_delete_schema import (
    RemindersDeleteSchema,
)
from slackwebapi.models.reminders_info_schema import (
    RemindersInfoSchema,
)
from slackwebapi.models.reminders_list_schema import (
    RemindersListSchema,
)


class RemindersController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize RemindersController object."""
        super(RemindersController, self).__init__(config)

    def reminders_add(self,
                      token,
                      text,
                      time,
                      user=None):
        """Perform a POST request to /reminders.add.

        Creates a reminder.

        Args:
            token (str): Authentication token. Requires scope: `reminders:write`
            text (str): The content of the reminder
            time (str): When this reminder should happen: the Unix timestamp (up to
                five years from now), the number of seconds until the reminder (if
                within 24 hours), or a natural language description (Ex. "in 15
                minutes," or "every Thursday")
            user (str, optional): The user who will receive the reminder. If no user
                is specified, the reminder will go to user who created it.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reminders.add")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("text")
                .value(text)
                .is_required(True))
            .form_param(Parameter()
                .key("time")
                .value(time)
                .is_required(True))
            .form_param(Parameter()
                .key("user")
                .value(user))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RemindersAddSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RemindersAddErrorSchemaException),
        ).execute()

    def reminders_complete(self,
                           token=None,
                           reminder=None):
        """Perform a POST request to /reminders.complete.

        Marks a reminder as complete.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `reminders:write`
            reminder (str, optional): The ID of the reminder to be marked as complete

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reminders.complete")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("reminder")
                .value(reminder))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RemindersCompleteSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RemindersCompleteErrorSchemaException),
        ).execute()

    def reminders_delete(self,
                         token=None,
                         reminder=None):
        """Perform a POST request to /reminders.delete.

        Deletes a reminder.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `reminders:write`
            reminder (str, optional): The ID of the reminder

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reminders.delete")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token))
            .form_param(Parameter()
                .key("reminder")
                .value(reminder))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RemindersDeleteSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RemindersDeleteErrorSchemaException),
        ).execute()

    def reminders_info(self,
                       token=None,
                       reminder=None):
        """Perform a GET request to /reminders.info.

        Gets information about a reminder.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `reminders:read`
            reminder (str, optional): The ID of the reminder

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reminders.info")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .query_param(Parameter()
                .key("reminder")
                .value(reminder))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RemindersInfoSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RemindersInfoErrorSchemaException),
        ).execute()

    def reminders_list(self,
                       token=None):
        """Perform a GET request to /reminders.list.

        Lists all reminders created by or for a given user.

        Args:
            token (str, optional): Authentication token. Requires scope:
                `reminders:read`

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/reminders.list")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("token")
                .value(token))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RemindersListSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RemindersListErrorSchemaException),
        ).execute()
