"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.rtm_connect_error_schema_exception import (
    RtmConnectErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.rtm_connect_schema import (
    RtmConnectSchema,
)


class RtmController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize RtmController object."""
        super(RtmController, self).__init__(config)

    def rtm_connect(self,
                    token,
                    batch_presence_aware=None,
                    presence_sub=None):
        """Perform a GET request to /rtm.connect.

        Starts a Real Time Messaging session.

        Args:
            token (str): Authentication token. Requires scope: `rtm:stream`
            batch_presence_aware (bool, optional): Batch presence deliveries via
                subscription. Enabling changes the shape of `presence_change` events.
                See [batch presence](/docs/presence-and-status#batching).
            presence_sub (bool, optional): Only deliver presence events when
                requested by subscription. See [presence
                subscriptions](/docs/presence-and-status#subscriptions).

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/rtm.connect")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("batch_presence_aware")
                .value(batch_presence_aware))
            .query_param(Parameter()
                .key("presence_sub")
                .value(presence_sub))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(RtmConnectSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                RtmConnectErrorSchemaException),
        ).execute()
