"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class SearchController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize SearchController object."""
        super(SearchController, self).__init__(config)

    def search_messages(self,
                        token,
                        query,
                        count=None,
                        highlight=None,
                        page=None,
                        sort=None,
                        sort_dir=None):
        """Perform a GET request to /search.messages.

        Searches for messages matching a query.

        Args:
            token (str): Authentication token. Requires scope: `search:read`
            query (str): Search query.
            count (int, optional): Pass the number of results you want per "page".
                Maximum of `100`.
            highlight (bool, optional): Pass a value of `true` to enable query
                highlight markers (see below).
            page (int, optional): The request query parameter.
            sort (str, optional): Return matches sorted by either `score` or
                `timestamp`.
            sort_dir (str, optional): Change sort direction to ascending (`asc`) or
                descending (`desc`).

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/search.messages")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("query")
                .value(query)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("count")
                .value(count))
            .query_param(Parameter()
                .key("highlight")
                .value(highlight))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("sort")
                .value(sort))
            .query_param(Parameter()
                .key("sort_dir")
                .value(sort_dir))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                DefaultErrorTemplateException),
        ).execute()
