"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.usergroups_create_error_schema_exception import (
    UsergroupsCreateErrorSchemaException,
)
from slackwebapi.exceptions.usergroups_disable_error_schema_exception import (
    UsergroupsDisableErrorSchemaException,
)
from slackwebapi.exceptions.usergroups_enable_error_schema_exception import (
    UsergroupsEnableErrorSchemaException,
)
from slackwebapi.exceptions.usergroups_list_error_schema_exception import (
    UsergroupsListErrorSchemaException,
)
from slackwebapi.exceptions.usergroups_update_error_schema_exception import (
    UsergroupsUpdateErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.usergroups_create_schema import (
    UsergroupsCreateSchema,
)
from slackwebapi.models.usergroups_disable_schema import (
    UsergroupsDisableSchema,
)
from slackwebapi.models.usergroups_enable_schema import (
    UsergroupsEnableSchema,
)
from slackwebapi.models.usergroups_list_schema import (
    UsergroupsListSchema,
)
from slackwebapi.models.usergroups_update_schema import (
    UsergroupsUpdateSchema,
)


class UsergroupsController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize UsergroupsController object."""
        super(UsergroupsController, self).__init__(config)

    def usergroups_create(self,
                          token,
                          name,
                          channels=None,
                          description=None,
                          handle=None,
                          include_count=None):
        """Perform a POST request to /usergroups.create.

        Create a User Group

        Args:
            token (str): Authentication token. Requires scope: `usergroups:write`
            name (str): A name for the User Group. Must be unique among User Groups.
            channels (str, optional): A comma separated string of encoded channel IDs
                for which the User Group uses as a default.
            description (str, optional): A short description of the User Group.
            handle (str, optional): A mention handle. Must be unique among channels,
                users and User Groups.
            include_count (bool, optional): Include the number of users in each User
                Group.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/usergroups.create")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("name")
                .value(name)
                .is_required(True))
            .form_param(Parameter()
                .key("channels")
                .value(channels))
            .form_param(Parameter()
                .key("description")
                .value(description))
            .form_param(Parameter()
                .key("handle")
                .value(handle))
            .form_param(Parameter()
                .key("include_count")
                .value(include_count))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsergroupsCreateSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsergroupsCreateErrorSchemaException),
        ).execute()

    def usergroups_disable(self,
                           token,
                           usergroup,
                           include_count=None):
        """Perform a POST request to /usergroups.disable.

        Disable an existing User Group

        Args:
            token (str): Authentication token. Requires scope: `usergroups:write`
            usergroup (str): The encoded ID of the User Group to disable.
            include_count (bool, optional): Include the number of users in the User
                Group.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/usergroups.disable")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("usergroup")
                .value(usergroup)
                .is_required(True))
            .form_param(Parameter()
                .key("include_count")
                .value(include_count))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsergroupsDisableSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsergroupsDisableErrorSchemaException),
        ).execute()

    def usergroups_enable(self,
                          token,
                          usergroup,
                          include_count=None):
        """Perform a POST request to /usergroups.enable.

        Enable a User Group

        Args:
            token (str): Authentication token. Requires scope: `usergroups:write`
            usergroup (str): The encoded ID of the User Group to enable.
            include_count (bool, optional): Include the number of users in the User
                Group.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/usergroups.enable")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("usergroup")
                .value(usergroup)
                .is_required(True))
            .form_param(Parameter()
                .key("include_count")
                .value(include_count))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsergroupsEnableSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsergroupsEnableErrorSchemaException),
        ).execute()

    def usergroups_list(self,
                        token,
                        include_users=None,
                        include_count=None,
                        include_disabled=None):
        """Perform a GET request to /usergroups.list.

        List all User Groups for a team

        Args:
            token (str): Authentication token. Requires scope: `usergroups:read`
            include_users (bool, optional): Include the list of users for each User
                Group.
            include_count (bool, optional): Include the number of users in each User
                Group.
            include_disabled (bool, optional): Include disabled User Groups.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/usergroups.list")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("include_users")
                .value(include_users))
            .query_param(Parameter()
                .key("include_count")
                .value(include_count))
            .query_param(Parameter()
                .key("include_disabled")
                .value(include_disabled))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsergroupsListSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsergroupsListErrorSchemaException),
        ).execute()

    def usergroups_update(self,
                          token,
                          usergroup,
                          handle=None,
                          description=None,
                          channels=None,
                          include_count=None,
                          name=None):
        """Perform a POST request to /usergroups.update.

        Update an existing User Group

        Args:
            token (str): Authentication token. Requires scope: `usergroups:write`
            usergroup (str): The encoded ID of the User Group to update.
            handle (str, optional): A mention handle. Must be unique among channels,
                users and User Groups.
            description (str, optional): A short description of the User Group.
            channels (str, optional): A comma separated string of encoded channel IDs
                for which the User Group uses as a default.
            include_count (bool, optional): Include the number of users in the User
                Group.
            name (str, optional): A name for the User Group. Must be unique among
                User Groups.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/usergroups.update")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("usergroup")
                .value(usergroup)
                .is_required(True))
            .form_param(Parameter()
                .key("handle")
                .value(handle))
            .form_param(Parameter()
                .key("description")
                .value(description))
            .form_param(Parameter()
                .key("channels")
                .value(channels))
            .form_param(Parameter()
                .key("include_count")
                .value(include_count))
            .form_param(Parameter()
                .key("name")
                .value(name))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsergroupsUpdateSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsergroupsUpdateErrorSchemaException),
        ).execute()
