"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.users_profile_get_error_schema_exception import (
    UsersProfileGetErrorSchemaException,
)
from slackwebapi.exceptions.users_profile_set_error_schema_exception import (
    UsersProfileSetErrorSchemaException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.users_profile_get_schema import (
    UsersProfileGetSchema,
)
from slackwebapi.models.users_profile_set_schema import (
    UsersProfileSetSchema,
)


class UsersProfileController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize UsersProfileController object."""
        super(UsersProfileController, self).__init__(config)

    def users_profile_get(self,
                          token,
                          include_labels=None,
                          user=None):
        """Perform a GET request to /users.profile.get.

        Retrieves a user's profile information.

        Args:
            token (str): Authentication token. Requires scope: `users.profile:read`
            include_labels (bool, optional): Include labels for each ID in custom
                profile fields
            user (str, optional): User to retrieve profile info for

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/users.profile.get")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("include_labels")
                .value(include_labels))
            .query_param(Parameter()
                .key("user")
                .value(user))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsersProfileGetSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsersProfileGetErrorSchemaException),
        ).execute()

    def users_profile_set(self,
                          token,
                          name=None,
                          profile=None,
                          user=None,
                          value=None):
        """Perform a POST request to /users.profile.set.

        Set the profile information for a user.

        Args:
            token (str): Authentication token. Requires scope: `users.profile:write`
            name (str, optional): Name of a single key to set. Usable only if
                `profile` is not passed.
            profile (str, optional): Collection of key:value pairs presented as a
                URL-encoded JSON hash. At most 50 fields may be set. Each field name
                is limited to 255 characters.
            user (str, optional): ID of user to change. This argument may only be
                specified by team admins on paid teams.
            value (str, optional): Value to set a single key to. Usable only if
                `profile` is not passed.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success response

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/users.profile.set")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .form_param(Parameter()
                .key("name")
                .value(name))
            .form_param(Parameter()
                .key("profile")
                .value(profile))
            .form_param(Parameter()
                .key("user")
                .value(user))
            .form_param(Parameter()
                .key("value")
                .value(value))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(UsersProfileSetSchema.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response",
                UsersProfileSetErrorSchemaException),
        ).execute()
