"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from slackwebapi.api_helper import APIHelper
from slackwebapi.configuration import Server
from slackwebapi.controllers.base_controller import (
    BaseController,
)
from slackwebapi.exceptions.default_error_template_exception import (
    DefaultErrorTemplateException,
)
from slackwebapi.http.http_method_enum import (
    HttpMethodEnum,
)
from slackwebapi.models.default_success_template import (
    DefaultSuccessTemplate,
)


class ViewsController(BaseController):
    """A Controller to access Endpoints in the slackwebapi API."""

    def __init__(self, config):
        """Initialize ViewsController object."""
        super(ViewsController, self).__init__(config)

    def views_open(self,
                   token,
                   trigger_id,
                   view):
        """Perform a GET request to /views.open.

        Open a view for a user.

        Args:
            token (str): Authentication token. Requires scope: `none`
            trigger_id (str): Exchange a trigger to post to the user.
            view (str): A [view payload](/reference/surfaces/views). This must be a
                JSON-encoded string.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response includes the opened view payload.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/views.open")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("trigger_id")
                .value(trigger_id)
                .is_required(True))
            .query_param(Parameter()
                .key("view")
                .value(view)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response, before getting to any possible validation er"
                "rors.",
                DefaultErrorTemplateException),
        ).execute()

    def views_publish(self,
                      token,
                      user_id,
                      view,
                      hash=None):
        """Perform a GET request to /views.publish.

        Publish a static view for a User.

        Args:
            token (str): Authentication token. Requires scope: `none`
            user_id (str): `id` of the user you want publish a view to.
            view (str): A [view payload](/reference/surfaces/views). This must be a
                JSON-encoded string.
            hash (str, optional): A string that represents view state to protect
                against possible race conditions.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response includes the published view payload.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/views.publish")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("user_id")
                .value(user_id)
                .is_required(True))
            .query_param(Parameter()
                .key("view")
                .value(view)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("hash")
                .value(hash))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response, before getting to any possible validation er"
                "rors.",
                DefaultErrorTemplateException),
        ).execute()

    def views_push(self,
                   token,
                   trigger_id,
                   view):
        """Perform a GET request to /views.push.

        Push a view onto the stack of a root view.

        Args:
            token (str): Authentication token. Requires scope: `none`
            trigger_id (str): Exchange a trigger to post to the user.
            view (str): A [view payload](/reference/surfaces/views). This must be a
                JSON-encoded string.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response includes the pushed view payload.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/views.push")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .query_param(Parameter()
                .key("trigger_id")
                .value(trigger_id)
                .is_required(True))
            .query_param(Parameter()
                .key("view")
                .value(view)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response.",
                DefaultErrorTemplateException),
        ).execute()

    def views_update(self,
                     token,
                     view_id=None,
                     external_id=None,
                     view=None,
                     hash=None):
        """Perform a GET request to /views.update.

        Update an existing view.

        Args:
            token (str): Authentication token. Requires scope: `none`
            view_id (str, optional): A unique identifier of the view to be updated.
                Either `view_id` or `external_id` is required.
            external_id (str, optional): A unique identifier of the view set by the
                developer. Must be unique for all views on a team. Max length of 255
                characters. Either `view_id` or `external_id` is required.
            view (str, optional): A [view object](/reference/surfaces/views). This
                must be a JSON-encoded string.
            hash (str, optional): A string that represents view state to protect
                against possible race conditions.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Typical success
                response includes the updated view payload.

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/views.update")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("token")
                .value(token)
                .is_required(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/x-www-form-urlencoded"))
            .query_param(Parameter()
                .key("view_id")
                .value(view_id))
            .query_param(Parameter()
                .key("external_id")
                .value(external_id))
            .query_param(Parameter()
                .key("view")
                .value(view))
            .query_param(Parameter()
                .key("hash")
                .value(hash))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("slackAuth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(DefaultSuccessTemplate.from_dictionary)
            .is_api_response(True)
            .local_error("default",
                "Typical error response.",
                DefaultErrorTemplateException),
        ).execute()
