"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.channel_object import (
    ChannelObject,
)


class AdminConversationsSearchSchema(object):
    """Implementation of the 'admin.conversations.search schema' model.

    Schema for successful response of admin.conversations.search

    Attributes:
        channels (List[ChannelObject]): The model property of type
            List[ChannelObject].
        next_cursor (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "channels": "channels",
        "next_cursor": "next_cursor",
    }

    def __init__(
        self,
        channels=None,
        next_cursor=None,
        additional_properties=None):
        """Initialize a AdminConversationsSearchSchema instance."""
        # Initialize members of the class
        self.channels = channels
        self.next_cursor = next_cursor

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        channels = None
        if dictionary.get("channels") is not None:
            channels = [
                ChannelObject.from_dictionary(x)
                    for x in dictionary.get("channels")
            ]
        next_cursor =\
            dictionary.get("next_cursor")\
            if dictionary.get("next_cursor")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(channels,
                   next_cursor,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _channels=self.channels
        _next_cursor=self.next_cursor
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channels={_channels!r}, "
            f"next_cursor={_next_cursor!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _channels=self.channels
        _next_cursor=self.next_cursor
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channels={_channels!s}, "
            f"next_cursor={_next_cursor!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
