"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ApiMethodUsersGetPresence(object):
    """Implementation of the 'API method: users.getPresence' model.

    Generated from users.getPresence with shasum
    e7251aec575d8863f9e0eb38663ae9dc26655f65

    Attributes:
        auto_away (bool): The model property of type bool.
        connection_count (int): The model property of type int.
        last_activity (int): The model property of type int.
        manual_away (bool): The model property of type bool.
        ok (str): The model property of type str.
        online (bool): The model property of type bool.
        presence (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "presence": "presence",
        "auto_away": "auto_away",
        "connection_count": "connection_count",
        "last_activity": "last_activity",
        "manual_away": "manual_away",
        "online": "online",
    }

    _optionals = [
        "auto_away",
        "connection_count",
        "last_activity",
        "manual_away",
        "online",
    ]

    def __init__(
        self,
        presence=None,
        auto_away=APIHelper.SKIP,
        connection_count=APIHelper.SKIP,
        last_activity=APIHelper.SKIP,
        manual_away=APIHelper.SKIP,
        online=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ApiMethodUsersGetPresence instance."""
        # Initialize members of the class
        if auto_away is not APIHelper.SKIP:
            self.auto_away = auto_away
        if connection_count is not APIHelper.SKIP:
            self.connection_count = connection_count
        if last_activity is not APIHelper.SKIP:
            self.last_activity = last_activity
        if manual_away is not APIHelper.SKIP:
            self.manual_away = manual_away
        self.ok = "True"
        if online is not APIHelper.SKIP:
            self.online = online
        self.presence = presence

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        presence =\
            dictionary.get("presence")\
            if dictionary.get("presence")\
                else None
        auto_away =\
            dictionary.get("auto_away")\
            if "auto_away" in dictionary.keys()\
                else APIHelper.SKIP
        connection_count =\
            dictionary.get("connection_count")\
            if dictionary.get("connection_count")\
                else APIHelper.SKIP
        last_activity =\
            dictionary.get("last_activity")\
            if dictionary.get("last_activity")\
                else APIHelper.SKIP
        manual_away =\
            dictionary.get("manual_away")\
            if "manual_away" in dictionary.keys()\
                else APIHelper.SKIP
        online =\
            dictionary.get("online")\
            if "online" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(presence,
                   auto_away,
                   connection_count,
                   last_activity,
                   manual_away,
                   online,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _auto_away=(
            self.auto_away
            if hasattr(self, "auto_away")
            else None
        )
        _connection_count=(
            self.connection_count
            if hasattr(self, "connection_count")
            else None
        )
        _last_activity=(
            self.last_activity
            if hasattr(self, "last_activity")
            else None
        )
        _manual_away=(
            self.manual_away
            if hasattr(self, "manual_away")
            else None
        )
        _ok=self.ok
        _online=(
            self.online
            if hasattr(self, "online")
            else None
        )
        _presence=self.presence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"auto_away={_auto_away!r}, "
            f"connection_count={_connection_count!r}, "
            f"last_activity={_last_activity!r}, "
            f"manual_away={_manual_away!r}, "
            f"ok={_ok!r}, "
            f"online={_online!r}, "
            f"presence={_presence!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _auto_away=(
            self.auto_away
            if hasattr(self, "auto_away")
            else None
        )
        _connection_count=(
            self.connection_count
            if hasattr(self, "connection_count")
            else None
        )
        _last_activity=(
            self.last_activity
            if hasattr(self, "last_activity")
            else None
        )
        _manual_away=(
            self.manual_away
            if hasattr(self, "manual_away")
            else None
        )
        _ok=self.ok
        _online=(
            self.online
            if hasattr(self, "online")
            else None
        )
        _presence=self.presence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"auto_away={_auto_away!s}, "
            f"connection_count={_connection_count!s}, "
            f"last_activity={_last_activity!s}, "
            f"manual_away={_manual_away!s}, "
            f"ok={_ok!s}, "
            f"online={_online!s}, "
            f"presence={_presence!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
