"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.info import Info


class AppsPermissionsInfoSchema(object):
    """Implementation of the 'apps.permissions.info schema' model.

    Schema for successful response from apps.permissions.info method

    Attributes:
        info (Info): The model property of type Info.
        ok (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "info": "info",
        "ok": "ok",
    }

    def __init__(
        self,
        info=None,
        additional_properties=None):
        """Initialize a AppsPermissionsInfoSchema instance."""
        # Initialize members of the class
        self.info = info
        self.ok = "True"

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        info =\
            Info.from_dictionary(
                dictionary.get("info"))\
                if dictionary.get("info") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(info,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _info=self.info
        _ok=self.ok
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"info={_info!r}, "
            f"ok={_ok!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _info=self.info
        _ok=self.ok
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"info={_info!s}, "
            f"ok={_ok!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
