"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.resource import Resource
from slackwebapi.models.response_metadata import (
    ResponseMetadata,
)


class AppsPermissionsResourcesListSuccessSchema(object):
    """Implementation of the 'apps.permissions.resources.list success schema' model.

    Schema for successful response apps.permissions.resources.list method

    Attributes:
        ok (str): The model property of type str.
        resources (List[Resource]): The model property of type List[Resource].
        response_metadata (ResponseMetadata): The model property of type
            ResponseMetadata.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "resources": "resources",
        "response_metadata": "response_metadata",
    }

    _optionals = [
        "response_metadata",
    ]

    def __init__(
        self,
        resources=None,
        response_metadata=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AppsPermissionsResourcesListSuccessSchema instance."""
        # Initialize members of the class
        self.ok = "True"
        self.resources = resources
        if response_metadata is not APIHelper.SKIP:
            self.response_metadata = response_metadata

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        resources = None
        if dictionary.get("resources") is not None:
            resources = [
                Resource.from_dictionary(x)
                    for x in dictionary.get("resources")
            ]
        response_metadata =\
            ResponseMetadata.from_dictionary(
                dictionary.get("response_metadata"))\
                if "response_metadata" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(resources,
                   response_metadata,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ok=self.ok
        _resources=self.resources
        _response_metadata=(
            self.response_metadata
            if hasattr(self, "response_metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!r}, "
            f"resources={_resources!r}, "
            f"response_metadata={_response_metadata!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ok=self.ok
        _resources=self.resources
        _response_metadata=(
            self.response_metadata
            if hasattr(self, "response_metadata")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!s}, "
            f"resources={_resources!s}, "
            f"response_metadata={_response_metadata!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
