"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class Attachment(object):
    """Implementation of the 'Attachment' model.

    Attributes:
        fallback (str): The model property of type str.
        id (int): The model property of type int.
        image_bytes (int): The model property of type int.
        image_height (int): The model property of type int.
        image_url (str): The model property of type str.
        image_width (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "fallback": "fallback",
        "image_bytes": "image_bytes",
        "image_height": "image_height",
        "image_url": "image_url",
        "image_width": "image_width",
    }

    _optionals = [
        "fallback",
        "image_bytes",
        "image_height",
        "image_url",
        "image_width",
    ]

    def __init__(
        self,
        id=None,
        fallback=APIHelper.SKIP,
        image_bytes=APIHelper.SKIP,
        image_height=APIHelper.SKIP,
        image_url=APIHelper.SKIP,
        image_width=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Attachment instance."""
        # Initialize members of the class
        if fallback is not APIHelper.SKIP:
            self.fallback = fallback
        self.id = id
        if image_bytes is not APIHelper.SKIP:
            self.image_bytes = image_bytes
        if image_height is not APIHelper.SKIP:
            self.image_height = image_height
        if image_url is not APIHelper.SKIP:
            self.image_url = image_url
        if image_width is not APIHelper.SKIP:
            self.image_width = image_width

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        fallback =\
            dictionary.get("fallback")\
            if dictionary.get("fallback")\
                else APIHelper.SKIP
        image_bytes =\
            dictionary.get("image_bytes")\
            if dictionary.get("image_bytes")\
                else APIHelper.SKIP
        image_height =\
            dictionary.get("image_height")\
            if dictionary.get("image_height")\
                else APIHelper.SKIP
        image_url =\
            dictionary.get("image_url")\
            if dictionary.get("image_url")\
                else APIHelper.SKIP
        image_width =\
            dictionary.get("image_width")\
            if dictionary.get("image_width")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   fallback,
                   image_bytes,
                   image_height,
                   image_url,
                   image_width,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _fallback=(
            self.fallback
            if hasattr(self, "fallback")
            else None
        )
        _id=self.id
        _image_bytes=(
            self.image_bytes
            if hasattr(self, "image_bytes")
            else None
        )
        _image_height=(
            self.image_height
            if hasattr(self, "image_height")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _image_width=(
            self.image_width
            if hasattr(self, "image_width")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"fallback={_fallback!r}, "
            f"id={_id!r}, "
            f"image_bytes={_image_bytes!r}, "
            f"image_height={_image_height!r}, "
            f"image_url={_image_url!r}, "
            f"image_width={_image_width!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _fallback=(
            self.fallback
            if hasattr(self, "fallback")
            else None
        )
        _id=self.id
        _image_bytes=(
            self.image_bytes
            if hasattr(self, "image_bytes")
            else None
        )
        _image_height=(
            self.image_height
            if hasattr(self, "image_height")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _image_width=(
            self.image_width
            if hasattr(self, "image_width")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"fallback={_fallback!s}, "
            f"id={_id!s}, "
            f"image_bytes={_image_bytes!s}, "
            f"image_height={_image_height!s}, "
            f"image_url={_image_url!s}, "
            f"image_width={_image_width!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
