"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.resources_in_info_from_apps_permissions_info import (
    ResourcesInInfoFromAppsPermissionsInfo,
)


class Channel(object):
    """Implementation of the 'Channel' model.

    Attributes:
        resources (ResourcesInInfoFromAppsPermissionsInfo): The model property of
            type ResourcesInInfoFromAppsPermissionsInfo.
        scopes (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "resources": "resources",
        "scopes": "scopes",
    }

    _optionals = [
        "resources",
        "scopes",
    ]

    def __init__(
        self,
        resources=APIHelper.SKIP,
        scopes=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Channel instance."""
        # Initialize members of the class
        if resources is not APIHelper.SKIP:
            self.resources = resources
        if scopes is not APIHelper.SKIP:
            self.scopes = scopes

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        resources =\
            ResourcesInInfoFromAppsPermissionsInfo.from_dictionary(
                dictionary.get("resources"))\
                if "resources" in dictionary.keys()\
                else APIHelper.SKIP
        scopes =\
            dictionary.get("scopes")\
            if dictionary.get("scopes")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(resources,
                   scopes,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _resources=(
            self.resources
            if hasattr(self, "resources")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"resources={_resources!r}, "
            f"scopes={_scopes!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _resources=(
            self.resources
            if hasattr(self, "resources")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"resources={_resources!s}, "
            f"scopes={_scopes!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
