"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.response_metadata import (
    ResponseMetadata,
)
from slackwebapi.models.scheduled_message import (
    ScheduledMessage,
)


class ChatScheduledMessagesListSchema(object):
    """Implementation of the 'chat.scheduledMessages.list schema' model.

    Schema for successful response from chat.scheduledMessages.list method

    Attributes:
        ok (str): The model property of type str.
        response_metadata (ResponseMetadata): The model property of type
            ResponseMetadata.
        scheduled_messages (List[ScheduledMessage]): The model property of type
            List[ScheduledMessage].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "response_metadata": "response_metadata",
        "scheduled_messages": "scheduled_messages",
    }

    def __init__(
        self,
        response_metadata=None,
        scheduled_messages=None,
        additional_properties=None):
        """Initialize a ChatScheduledMessagesListSchema instance."""
        # Initialize members of the class
        self.ok = "True"
        self.response_metadata = response_metadata
        self.scheduled_messages = scheduled_messages

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        response_metadata =\
            ResponseMetadata.from_dictionary(
                dictionary.get("response_metadata"))\
                if dictionary.get("response_metadata") else None
        scheduled_messages = None
        if dictionary.get("scheduled_messages") is not None:
            scheduled_messages = [
                ScheduledMessage.from_dictionary(x)
                    for x in dictionary.get("scheduled_messages")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(response_metadata,
                   scheduled_messages,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ok=self.ok
        _response_metadata=self.response_metadata
        _scheduled_messages=self.scheduled_messages
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!r}, "
            f"response_metadata={_response_metadata!r}, "
            f"scheduled_messages={_scheduled_messages!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ok=self.ok
        _response_metadata=self.response_metadata
        _scheduled_messages=self.scheduled_messages
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!s}, "
            f"response_metadata={_response_metadata!s}, "
            f"scheduled_messages={_scheduled_messages!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
