"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.response_metadata_3 import (
    ResponseMetadata3,
)


class ConversationsJoinSuccessSchema(object):
    """Implementation of the 'conversations.join success schema' model.

    Schema for successful response from conversations.join method

    Attributes:
        channel (Any): The model property of type Any.
        ok (str): The model property of type str.
        response_metadata (ResponseMetadata3): The model property of type
            ResponseMetadata3.
        warning (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "channel": "channel",
        "ok": "ok",
        "response_metadata": "response_metadata",
        "warning": "warning",
    }

    _optionals = [
        "response_metadata",
        "warning",
    ]

    def __init__(
        self,
        channel=None,
        response_metadata=APIHelper.SKIP,
        warning=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ConversationsJoinSuccessSchema instance."""
        # Initialize members of the class
        self.channel = channel
        self.ok = "True"
        if response_metadata is not APIHelper.SKIP:
            self.response_metadata = response_metadata
        if warning is not APIHelper.SKIP:
            self.warning = warning

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        channel =\
            dictionary.get("channel")\
            if dictionary.get("channel")\
                else None
        response_metadata =\
            ResponseMetadata3.from_dictionary(
                dictionary.get("response_metadata"))\
                if "response_metadata" in dictionary.keys()\
                else APIHelper.SKIP
        warning =\
            dictionary.get("warning")\
            if dictionary.get("warning")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(channel,
                   response_metadata,
                   warning,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _channel=self.channel
        _ok=self.ok
        _response_metadata=(
            self.response_metadata
            if hasattr(self, "response_metadata")
            else None
        )
        _warning=(
            self.warning
            if hasattr(self, "warning")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channel={_channel!r}, "
            f"ok={_ok!r}, "
            f"response_metadata={_response_metadata!r}, "
            f"warning={_warning!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _channel=self.channel
        _ok=self.ok
        _response_metadata=(
            self.response_metadata
            if hasattr(self, "response_metadata")
            else None
        )
        _warning=(
            self.warning
            if hasattr(self, "warning")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channel={_channel!s}, "
            f"ok={_ok!s}, "
            f"response_metadata={_response_metadata!s}, "
            f"warning={_warning!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
