"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ConversationsOpenSuccessSchema(object):
    """Implementation of the 'conversations.open success schema' model.

    Schema for successful response from conversations.open method when opening
    channels, ims, mpims

    Attributes:
        already_open (bool): The model property of type bool.
        channel (Any): The model property of type Any.
        no_op (bool): The model property of type bool.
        ok (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "channel": "channel",
        "ok": "ok",
        "already_open": "already_open",
        "no_op": "no_op",
    }

    _optionals = [
        "already_open",
        "no_op",
    ]

    def __init__(
        self,
        channel=None,
        already_open=APIHelper.SKIP,
        no_op=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ConversationsOpenSuccessSchema instance."""
        # Initialize members of the class
        if already_open is not APIHelper.SKIP:
            self.already_open = already_open
        self.channel = channel
        if no_op is not APIHelper.SKIP:
            self.no_op = no_op
        self.ok = "True"

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        channel =\
            dictionary.get("channel")\
            if dictionary.get("channel")\
                else None
        already_open =\
            dictionary.get("already_open")\
            if "already_open" in dictionary.keys()\
                else APIHelper.SKIP
        no_op =\
            dictionary.get("no_op")\
            if "no_op" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(channel,
                   already_open,
                   no_op,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _already_open=(
            self.already_open
            if hasattr(self, "already_open")
            else None
        )
        _channel=self.channel
        _no_op=(
            self.no_op
            if hasattr(self, "no_op")
            else None
        )
        _ok=self.ok
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"already_open={_already_open!r}, "
            f"channel={_channel!r}, "
            f"no_op={_no_op!r}, "
            f"ok={_ok!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _already_open=(
            self.already_open
            if hasattr(self, "already_open")
            else None
        )
        _channel=self.channel
        _no_op=(
            self.no_op
            if hasattr(self, "no_op")
            else None
        )
        _ok=self.ok
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"already_open={_already_open!s}, "
            f"channel={_channel!s}, "
            f"no_op={_no_op!s}, "
            f"ok={_ok!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
