"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error96(object):
    """Implementation of the 'Error96' enum.

    Attributes:
        RESERVED_NAME: The enum member of type str.
        INVALID_PROFILE: The enum member of type str.
        PROFILE_SET_FAILED: The enum member of type str.
        NOT_ADMIN: The enum member of type str.
        NOT_APP_ADMIN: The enum member of type str.
        CANNOT_UPDATE_ADMIN_USER: The enum member of type str.
        NOT_AUTHED: The enum member of type str.
        INVALID_AUTH: The enum member of type str.
        ACCOUNT_INACTIVE: The enum member of type str.
        TOKEN_REVOKED: The enum member of type str.
        NO_PERMISSION: The enum member of type str.
        ORG_LOGIN_REQUIRED: The enum member of type str.
        USER_IS_BOT: The enum member of type str.
        INVALID_ARG_NAME: The enum member of type str.
        INVALID_ARRAY_ARG: The enum member of type str.
        INVALID_CHARSET: The enum member of type str.
        INVALID_FORM_DATA: The enum member of type str.
        INVALID_POST_TYPE: The enum member of type str.
        MISSING_POST_TYPE: The enum member of type str.
        TEAM_ADDED_TO_ORG: The enum member of type str.
        INVALID_JSON: The enum member of type str.
        JSON_NOT_OBJECT: The enum member of type str.
        REQUEST_TIMEOUT: The enum member of type str.
        UPGRADE_REQUIRED: The enum member of type str.
        FATAL_ERROR: The enum member of type str.

    """

    RESERVED_NAME = "reserved_name"

    INVALID_PROFILE = "invalid_profile"

    PROFILE_SET_FAILED = "profile_set_failed"

    NOT_ADMIN = "not_admin"

    NOT_APP_ADMIN = "not_app_admin"

    CANNOT_UPDATE_ADMIN_USER = "cannot_update_admin_user"

    NOT_AUTHED = "not_authed"

    INVALID_AUTH = "invalid_auth"

    ACCOUNT_INACTIVE = "account_inactive"

    TOKEN_REVOKED = "token_revoked"

    NO_PERMISSION = "no_permission"

    ORG_LOGIN_REQUIRED = "org_login_required"

    USER_IS_BOT = "user_is_bot"

    INVALID_ARG_NAME = "invalid_arg_name"

    INVALID_ARRAY_ARG = "invalid_array_arg"

    INVALID_CHARSET = "invalid_charset"

    INVALID_FORM_DATA = "invalid_form_data"

    INVALID_POST_TYPE = "invalid_post_type"

    MISSING_POST_TYPE = "missing_post_type"

    TEAM_ADDED_TO_ORG = "team_added_to_org"

    INVALID_JSON = "invalid_json"

    JSON_NOT_OBJECT = "json_not_object"

    REQUEST_TIMEOUT = "request_timeout"

    UPGRADE_REQUIRED = "upgrade_required"

    FATAL_ERROR = "fatal_error"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
