"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error5(object):
    """Implementation of the 'Error5' enum.

    Attributes:
        FEATURE_NOT_ENABLED: The enum member of type str.
        NOT_AN_ADMIN: The enum member of type str.
        NOT_AN_ENTERPRISE: The enum member of type str.
        RESTRICTED_ACTION: The enum member of type str.
        MISSING_SCOPE: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        CHANNEL_TYPE_NOT_SUPPORTED: The enum member of type str.
        COULD_NOT_GET_CONVERSATION_PREFS: The enum member of type str.

    """

    FEATURE_NOT_ENABLED = "feature_not_enabled"

    NOT_AN_ADMIN = "not_an_admin"

    NOT_AN_ENTERPRISE = "not_an_enterprise"

    RESTRICTED_ACTION = "restricted_action"

    MISSING_SCOPE = "missing_scope"

    CHANNEL_NOT_FOUND = "channel_not_found"

    CHANNEL_TYPE_NOT_SUPPORTED = "channel_type_not_supported"

    COULD_NOT_GET_CONVERSATION_PREFS = "could_not_get_conversation_prefs"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
