"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error7(object):
    """Implementation of the 'Error7' enum.

    Attributes:
        FEATURE_NOT_ENABLED: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        CHANNEL_TYPE_NOT_SUPPORTED: The enum member of type str.
        DEFAULT_ORG_WIDE_CHANNEL: The enum member of type str.
        RESTRICTED_ACTION: The enum member of type str.
        USER_MUST_BE_ADMIN: The enum member of type str.
        FAILED_FOR_SOME_USERS: The enum member of type str.

    """

    FEATURE_NOT_ENABLED = "feature_not_enabled"

    CHANNEL_NOT_FOUND = "channel_not_found"

    CHANNEL_TYPE_NOT_SUPPORTED = "channel_type_not_supported"

    DEFAULT_ORG_WIDE_CHANNEL = "default_org_wide_channel"

    RESTRICTED_ACTION = "restricted_action"

    USER_MUST_BE_ADMIN = "user_must_be_admin"

    FAILED_FOR_SOME_USERS = "failed_for_some_users"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
