"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error35(object):
    """Implementation of the 'Error35' enum.

    Attributes:
        METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE: The enum member of type str.
        MISSING_SCOPE: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        USER_NOT_FOUND: The enum member of type str.
        NO_USER: The enum member of type str.
        CANT_INVITE_SELF: The enum member of type str.
        NOT_IN_CHANNEL: The enum member of type str.
        ALREADY_IN_CHANNEL: The enum member of type str.
        IS_ARCHIVED: The enum member of type str.
        CANT_INVITE: The enum member of type str.
        TOO_MANY_USERS: The enum member of type str.
        URA_MAX_CHANNELS: The enum member of type str.
        NOT_AUTHED: The enum member of type str.
        INVALID_AUTH: The enum member of type str.
        ACCOUNT_INACTIVE: The enum member of type str.
        USER_IS_BOT: The enum member of type str.
        USER_IS_RESTRICTED: The enum member of type str.
        USER_IS_ULTRA_RESTRICTED: The enum member of type str.
        INVALID_ARG_NAME: The enum member of type str.
        INVALID_ARRAY_ARG: The enum member of type str.
        INVALID_CHARSET: The enum member of type str.
        INVALID_FORM_DATA: The enum member of type str.
        INVALID_POST_TYPE: The enum member of type str.
        MISSING_POST_TYPE: The enum member of type str.
        INVALID_JSON: The enum member of type str.
        JSON_NOT_OBJECT: The enum member of type str.
        REQUEST_TIMEOUT: The enum member of type str.
        UPGRADE_REQUIRED: The enum member of type str.
        TEAM_ADDED_TO_ORG: The enum member of type str.
        MISSING_CHARSET: The enum member of type str.
        SUPERFLUOUS_CHARSET: The enum member of type str.

    """

    METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE = "method_not_supported_for_channel_type"

    MISSING_SCOPE = "missing_scope"

    CHANNEL_NOT_FOUND = "channel_not_found"

    USER_NOT_FOUND = "user_not_found"

    NO_USER = "no_user"

    CANT_INVITE_SELF = "cant_invite_self"

    NOT_IN_CHANNEL = "not_in_channel"

    ALREADY_IN_CHANNEL = "already_in_channel"

    IS_ARCHIVED = "is_archived"

    CANT_INVITE = "cant_invite"

    TOO_MANY_USERS = "too_many_users"

    URA_MAX_CHANNELS = "ura_max_channels"

    NOT_AUTHED = "not_authed"

    INVALID_AUTH = "invalid_auth"

    ACCOUNT_INACTIVE = "account_inactive"

    USER_IS_BOT = "user_is_bot"

    USER_IS_RESTRICTED = "user_is_restricted"

    USER_IS_ULTRA_RESTRICTED = "user_is_ultra_restricted"

    INVALID_ARG_NAME = "invalid_arg_name"

    INVALID_ARRAY_ARG = "invalid_array_arg"

    INVALID_CHARSET = "invalid_charset"

    INVALID_FORM_DATA = "invalid_form_data"

    INVALID_POST_TYPE = "invalid_post_type"

    MISSING_POST_TYPE = "missing_post_type"

    INVALID_JSON = "invalid_json"

    JSON_NOT_OBJECT = "json_not_object"

    REQUEST_TIMEOUT = "request_timeout"

    UPGRADE_REQUIRED = "upgrade_required"

    TEAM_ADDED_TO_ORG = "team_added_to_org"

    MISSING_CHARSET = "missing_charset"

    SUPERFLUOUS_CHARSET = "superfluous_charset"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
