"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error55(object):
    """Implementation of the 'Error55' enum.

    Attributes:
        FILE_NOT_FOUND: The enum member of type str.
        FILE_DELETED: The enum member of type str.
        CANT_DELETE_FILE: The enum member of type str.
        NOT_AUTHED: The enum member of type str.
        INVALID_AUTH: The enum member of type str.
        ACCOUNT_INACTIVE: The enum member of type str.
        NO_PERMISSION: The enum member of type str.
        INVALID_ARG_NAME: The enum member of type str.
        INVALID_ARRAY_ARG: The enum member of type str.
        INVALID_CHARSET: The enum member of type str.
        INVALID_FORM_DATA: The enum member of type str.
        INVALID_POST_TYPE: The enum member of type str.
        MISSING_POST_TYPE: The enum member of type str.
        TEAM_ADDED_TO_ORG: The enum member of type str.
        INVALID_JSON: The enum member of type str.
        JSON_NOT_OBJECT: The enum member of type str.
        REQUEST_TIMEOUT: The enum member of type str.
        UPGRADE_REQUIRED: The enum member of type str.

    """

    FILE_NOT_FOUND = "file_not_found"

    FILE_DELETED = "file_deleted"

    CANT_DELETE_FILE = "cant_delete_file"

    NOT_AUTHED = "not_authed"

    INVALID_AUTH = "invalid_auth"

    ACCOUNT_INACTIVE = "account_inactive"

    NO_PERMISSION = "no_permission"

    INVALID_ARG_NAME = "invalid_arg_name"

    INVALID_ARRAY_ARG = "invalid_array_arg"

    INVALID_CHARSET = "invalid_charset"

    INVALID_FORM_DATA = "invalid_form_data"

    INVALID_POST_TYPE = "invalid_post_type"

    MISSING_POST_TYPE = "missing_post_type"

    TEAM_ADDED_TO_ORG = "team_added_to_org"

    INVALID_JSON = "invalid_json"

    JSON_NOT_OBJECT = "json_not_object"

    REQUEST_TIMEOUT = "request_timeout"

    UPGRADE_REQUIRED = "upgrade_required"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
