"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error1(object):
    """Implementation of the 'Error1' enum.

    Attributes:
        FEATURE_NOT_ENABLED: The enum member of type str.
        RESTRICTED_ACTION: The enum member of type str.
        NAME_TAKEN: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        CHANNEL_TYPE_NOT_SUPPORTED: The enum member of type str.
        DEFAULT_ORG_WIDE_CHANNEL: The enum member of type str.
        METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE: The enum member of type str.
        COULD_NOT_CONVERT_CHANNEL: The enum member of type str.
        EXTERNAL_CHANNEL_MIGRATING: The enum member of type str.

    """

    FEATURE_NOT_ENABLED = "feature_not_enabled"

    RESTRICTED_ACTION = "restricted_action"

    NAME_TAKEN = "name_taken"

    CHANNEL_NOT_FOUND = "channel_not_found"

    CHANNEL_TYPE_NOT_SUPPORTED = "channel_type_not_supported"

    DEFAULT_ORG_WIDE_CHANNEL = "default_org_wide_channel"

    METHOD_NOT_SUPPORTED_FOR_CHANNEL_TYPE = "method_not_supported_for_channel_type"

    COULD_NOT_CONVERT_CHANNEL = "could_not_convert_channel"

    EXTERNAL_CHANNEL_MIGRATING = "external_channel_migrating"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
