"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error4(object):
    """Implementation of the 'Error4' enum.

    Attributes:
        FEATURE_NOT_ENABLED: The enum member of type str.
        NOT_AN_ADMIN: The enum member of type str.
        NOT_AN_ENTERPRISE: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        NOT_SUPPORTED: The enum member of type str.
        TEAM_NOT_FOUND: The enum member of type str.
        RESTRICTED_ACTION: The enum member of type str.
        MISSING_SCOPE: The enum member of type str.
        LEAVING_TEAM_NOT_IN_CHANNEL: The enum member of type str.
        NO_TEAMS_TO_DISCONNECT: The enum member of type str.
        LEAVING_TEAM_REQUIRED: The enum member of type str.
        CANNOT_KICK_TEAM: The enum member of type str.
        CANNOT_KICK_HOME_TEAM: The enum member of type str.

    """

    FEATURE_NOT_ENABLED = "feature_not_enabled"

    NOT_AN_ADMIN = "not_an_admin"

    NOT_AN_ENTERPRISE = "not_an_enterprise"

    CHANNEL_NOT_FOUND = "channel_not_found"

    NOT_SUPPORTED = "not_supported"

    TEAM_NOT_FOUND = "team_not_found"

    RESTRICTED_ACTION = "restricted_action"

    MISSING_SCOPE = "missing_scope"

    LEAVING_TEAM_NOT_IN_CHANNEL = "leaving_team_not_in_channel"

    NO_TEAMS_TO_DISCONNECT = "no_teams_to_disconnect"

    LEAVING_TEAM_REQUIRED = "leaving_team_required"

    CANNOT_KICK_TEAM = "cannot_kick_team"

    CANNOT_KICK_HOME_TEAM = "cannot_kick_home_team"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
