"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Error6(object):
    """Implementation of the 'Error6' enum.

    Attributes:
        FEATURE_NOT_ENABLED: The enum member of type str.
        CHANNEL_NOT_FOUND: The enum member of type str.
        CHANNEL_TYPE_NOT_SUPPORTED: The enum member of type str.
        UNSUPPORTED_TEAM_TYPE: The enum member of type str.
        RESTRICTED_ACTION: The enum member of type str.
        COULD_NOT_GET_TEAMS: The enum member of type str.
        INVALID_CURSOR: The enum member of type str.
        INVALID_LIMIT: The enum member of type str.

    """

    FEATURE_NOT_ENABLED = "feature_not_enabled"

    CHANNEL_NOT_FOUND = "channel_not_found"

    CHANNEL_TYPE_NOT_SUPPORTED = "channel_type_not_supported"

    UNSUPPORTED_TEAM_TYPE = "unsupported_team_type"

    RESTRICTED_ACTION = "restricted_action"

    COULD_NOT_GET_TEAMS = "could_not_get_teams"

    INVALID_CURSOR = "invalid_cursor"

    INVALID_LIMIT = "invalid_limit"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
