"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.app_home import AppHome
from slackwebapi.models.channel import Channel
from slackwebapi.models.group import Group
from slackwebapi.models.im import Im
from slackwebapi.models.mpim import Mpim
from slackwebapi.models.team import Team


class Info(object):
    """Implementation of the 'Info' model.

    Attributes:
        app_home (AppHome): The model property of type AppHome.
        channel (Channel): The model property of type Channel.
        group (Group): The model property of type Group.
        im (Im): The model property of type Im.
        mpim (Mpim): The model property of type Mpim.
        team (Team): The model property of type Team.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "app_home": "app_home",
        "channel": "channel",
        "group": "group",
        "im": "im",
        "mpim": "mpim",
        "team": "team",
    }

    def __init__(
        self,
        app_home=None,
        channel=None,
        group=None,
        im=None,
        mpim=None,
        team=None,
        additional_properties=None):
        """Initialize a Info instance."""
        # Initialize members of the class
        self.app_home = app_home
        self.channel = channel
        self.group = group
        self.im = im
        self.mpim = mpim
        self.team = team

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        app_home =\
            AppHome.from_dictionary(
                dictionary.get("app_home"))\
                if dictionary.get("app_home") else None
        channel =\
            Channel.from_dictionary(
                dictionary.get("channel"))\
                if dictionary.get("channel") else None
        group =\
            Group.from_dictionary(
                dictionary.get("group"))\
                if dictionary.get("group") else None
        im =\
            Im.from_dictionary(
                dictionary.get("im"))\
                if dictionary.get("im") else None
        mpim =\
            Mpim.from_dictionary(
                dictionary.get("mpim"))\
                if dictionary.get("mpim") else None
        team =\
            Team.from_dictionary(
                dictionary.get("team"))\
                if dictionary.get("team") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(app_home,
                   channel,
                   group,
                   im,
                   mpim,
                   team,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _app_home=self.app_home
        _channel=self.channel
        _group=self.group
        _im=self.im
        _mpim=self.mpim
        _team=self.team
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"app_home={_app_home!r}, "
            f"channel={_channel!r}, "
            f"group={_group!r}, "
            f"im={_im!r}, "
            f"mpim={_mpim!r}, "
            f"team={_team!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _app_home=self.app_home
        _channel=self.channel
        _group=self.group
        _im=self.im
        _mpim=self.mpim
        _team=self.team
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"app_home={_app_home!s}, "
            f"channel={_channel!s}, "
            f"group={_group!s}, "
            f"im={_im!s}, "
            f"mpim={_mpim!s}, "
            f"team={_team!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
