"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class OauthScope(object):
    """Implementation of the 'OAuth Scope' enum.

    OAuth 2 scopes supported by the API

    Attributes:
        ADMIN: admin
        ADMIN.APPSREAD: admin.apps:read
        ADMIN.APPSWRITE: admin.apps:write
        ADMIN.CONVERSATIONSREAD: admin.conversations:read
        ADMIN.CONVERSATIONSWRITE: admin.conversations:write
        ADMIN.INVITESREAD: admin.invites:read
        ADMIN.INVITESWRITE: admin.invites:write
        ADMIN.TEAMSREAD: admin.teams:read
        ADMIN.TEAMSWRITE: admin.teams:write
        ADMIN.USERGROUPSREAD: admin.usergroups:read
        ADMIN.USERGROUPSWRITE: admin.usergroups:write
        ADMIN.USERSREAD: admin.users:read
        ADMIN.USERSWRITE: admin.users:write
        AUTHORIZATIONSREAD: authorizations:read
        BOT: Bot user scope
        CALLSREAD: calls:read
        CALLSWRITE: calls:write
        CHANNELSHISTORY: channels:history
        CHANNELSMANAGE: channels:manage
        CHANNELSREAD: channels:read
        CHANNELSWRITE: channels:write
        CHATWRITE: chat:write
        CHATWRITEBOT: Author messages as a bot
        CHATWRITEUSER: Author messages as a user
        CONVERSATIONSHISTORY: conversations:history
        CONVERSATIONSREAD: conversations:read
        CONVERSATIONSWRITE: conversations:write
        DNDREAD: dnd:read
        DNDWRITE: dnd:write
        EMOJIREAD: emoji:read
        FILESREAD: files:read
        FILESWRITEUSER: files:write:user
        GROUPSHISTORY: groups:history
        GROUPSREAD: groups:read
        GROUPSWRITE: groups:write
        IDENTITY.BASIC: identity.basic
        IMHISTORY: im:history
        IMREAD: im:read
        IMWRITE: im:write
        LINKSWRITE: links:write
        MPIMHISTORY: mpim:history
        MPIMREAD: mpim:read
        MPIMWRITE: mpim:write
        NONE: No scope required
        PINSREAD: pins:read
        PINSWRITE: pins:write
        REACTIONSREAD: reactions:read
        REACTIONSWRITE: reactions:write
        REMINDERSREAD: reminders:read
        REMINDERSWRITE: reminders:write
        REMOTE_FILESREAD: remote_files:read
        REMOTE_FILESSHARE: remote_files:share
        REMOTE_FILESWRITE: remote_files:write
        RTMSTREAM: rtm:stream
        SEARCHREAD: search:read
        STARSREAD: stars:read
        STARSWRITE: stars:write
        TEAMREAD: team:read
        TOKENS.BASIC: tokens.basic
        USERGROUPSREAD: usergroups:read
        USERGROUPSWRITE: usergroups:write
        USERS.PROFILEREAD: users.profile:read
        USERS.PROFILEWRITE: users.profile:write
        USERSREAD: users:read
        USERSREAD.EMAIL: users:read.email
        USERSWRITE: users:write
        WORKFLOW.STEPSEXECUTE: workflow.steps:execute

    """

    ADMIN = "admin"

    ADMIN_APPSREAD = "admin.apps:read"

    ADMIN_APPSWRITE = "admin.apps:write"

    ADMIN_CONVERSATIONSREAD = "admin.conversations:read"

    ADMIN_CONVERSATIONSWRITE = "admin.conversations:write"

    ADMIN_INVITESREAD = "admin.invites:read"

    ADMIN_INVITESWRITE = "admin.invites:write"

    ADMIN_TEAMSREAD = "admin.teams:read"

    ADMIN_TEAMSWRITE = "admin.teams:write"

    ADMIN_USERGROUPSREAD = "admin.usergroups:read"

    ADMIN_USERGROUPSWRITE = "admin.usergroups:write"

    ADMIN_USERSREAD = "admin.users:read"

    ADMIN_USERSWRITE = "admin.users:write"

    AUTHORIZATIONSREAD = "authorizations:read"

    BOT = "bot"

    CALLSREAD = "calls:read"

    CALLSWRITE = "calls:write"

    CHANNELSHISTORY = "channels:history"

    CHANNELSMANAGE = "channels:manage"

    CHANNELSREAD = "channels:read"

    CHANNELSWRITE = "channels:write"

    CHATWRITE = "chat:write"

    CHATWRITEBOT = "chat:write:bot"

    CHATWRITEUSER = "chat:write:user"

    CONVERSATIONSHISTORY = "conversations:history"

    CONVERSATIONSREAD = "conversations:read"

    CONVERSATIONSWRITE = "conversations:write"

    DNDREAD = "dnd:read"

    DNDWRITE = "dnd:write"

    EMOJIREAD = "emoji:read"

    FILESREAD = "files:read"

    FILESWRITEUSER = "files:write:user"

    GROUPSHISTORY = "groups:history"

    GROUPSREAD = "groups:read"

    GROUPSWRITE = "groups:write"

    IDENTITY_BASIC = "identity.basic"

    IMHISTORY = "im:history"

    IMREAD = "im:read"

    IMWRITE = "im:write"

    LINKSWRITE = "links:write"

    MPIMHISTORY = "mpim:history"

    MPIMREAD = "mpim:read"

    MPIMWRITE = "mpim:write"

    NONE = "none"

    PINSREAD = "pins:read"

    PINSWRITE = "pins:write"

    REACTIONSREAD = "reactions:read"

    REACTIONSWRITE = "reactions:write"

    REMINDERSREAD = "reminders:read"

    REMINDERSWRITE = "reminders:write"

    REMOTE_FILESREAD = "remote_files:read"

    REMOTE_FILESSHARE = "remote_files:share"

    REMOTE_FILESWRITE = "remote_files:write"

    RTMSTREAM = "rtm:stream"

    SEARCHREAD = "search:read"

    STARSREAD = "stars:read"

    STARSWRITE = "stars:write"

    TEAMREAD = "team:read"

    TOKENS_BASIC = "tokens.basic"

    USERGROUPSREAD = "usergroups:read"

    USERGROUPSWRITE = "usergroups:write"

    USERS_PROFILEREAD = "users.profile:read"

    USERS_PROFILEWRITE = "users.profile:write"

    USERSREAD = "users:read"

    USERSREAD_EMAIL = "users:read.email"

    USERSWRITE = "users:write"

    WORKFLOW_STEPSEXECUTE = "workflow.steps:execute"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
