"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ObjsTeamProfileField(object):
    """Implementation of the 'objs_team_profile_field' model.

    Attributes:
        field_name (str): The model property of type str.
        hint (str): The model property of type str.
        id (str): The model property of type str.
        is_hidden (bool): The model property of type bool.
        label (str): The model property of type str.
        options (Any): The model property of type Any.
        ordering (float): The model property of type float.
        possible_values (List[str]): The model property of type List[str].
        mtype (Type): The model property of type Type.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "hint": "hint",
        "id": "id",
        "label": "label",
        "ordering": "ordering",
        "mtype": "type",
        "field_name": "field_name",
        "is_hidden": "is_hidden",
        "options": "options",
        "possible_values": "possible_values",
    }

    _optionals = [
        "field_name",
        "is_hidden",
        "options",
        "possible_values",
    ]

    _nullables = [
        "field_name",
        "possible_values",
    ]

    def __init__(
        self,
        hint=None,
        id=None,
        label=None,
        ordering=None,
        mtype=None,
        field_name=APIHelper.SKIP,
        is_hidden=APIHelper.SKIP,
        options=APIHelper.SKIP,
        possible_values=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ObjsTeamProfileField instance."""
        # Initialize members of the class
        if field_name is not APIHelper.SKIP:
            self.field_name = field_name
        self.hint = hint
        self.id = id
        if is_hidden is not APIHelper.SKIP:
            self.is_hidden = is_hidden
        self.label = label
        if options is not APIHelper.SKIP:
            self.options = options
        self.ordering = ordering
        if possible_values is not APIHelper.SKIP:
            self.possible_values = possible_values
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        hint =\
            dictionary.get("hint")\
            if dictionary.get("hint")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        label =\
            dictionary.get("label")\
            if dictionary.get("label")\
                else None
        ordering =\
            dictionary.get("ordering")\
            if dictionary.get("ordering")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        field_name =\
            dictionary.get("field_name")\
            if "field_name" in dictionary.keys()\
                else APIHelper.SKIP
        is_hidden =\
            dictionary.get("is_hidden")\
            if "is_hidden" in dictionary.keys()\
                else APIHelper.SKIP
        options =\
            dictionary.get("options")\
            if dictionary.get("options")\
                else APIHelper.SKIP
        possible_values =\
            dictionary.get("possible_values")\
            if "possible_values" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(hint,
                   id,
                   label,
                   ordering,
                   mtype,
                   field_name,
                   is_hidden,
                   options,
                   possible_values,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _field_name=(
            self.field_name
            if hasattr(self, "field_name")
            else None
        )
        _hint=self.hint
        _id=self.id
        _is_hidden=(
            self.is_hidden
            if hasattr(self, "is_hidden")
            else None
        )
        _label=self.label
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _ordering=self.ordering
        _possible_values=(
            self.possible_values
            if hasattr(self, "possible_values")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field_name={_field_name!r}, "
            f"hint={_hint!r}, "
            f"id={_id!r}, "
            f"is_hidden={_is_hidden!r}, "
            f"label={_label!r}, "
            f"options={_options!r}, "
            f"ordering={_ordering!r}, "
            f"possible_values={_possible_values!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _field_name=(
            self.field_name
            if hasattr(self, "field_name")
            else None
        )
        _hint=self.hint
        _id=self.id
        _is_hidden=(
            self.is_hidden
            if hasattr(self, "is_hidden")
            else None
        )
        _label=self.label
        _options=(
            self.options
            if hasattr(self, "options")
            else None
        )
        _ordering=self.ordering
        _possible_values=(
            self.possible_values
            if hasattr(self, "possible_values")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"field_name={_field_name!s}, "
            f"hint={_hint!s}, "
            f"id={_id!s}, "
            f"is_hidden={_is_hidden!s}, "
            f"label={_label!s}, "
            f"options={_options!s}, "
            f"ordering={_ordering!s}, "
            f"possible_values={_possible_values!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
