"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ObjsIcon(object):
    """Implementation of the 'objs_icon' model.

    Attributes:
        image_102 (str): The model property of type str.
        image_132 (str): The model property of type str.
        image_230 (str): The model property of type str.
        image_34 (str): The model property of type str.
        image_44 (str): The model property of type str.
        image_68 (str): The model property of type str.
        image_88 (str): The model property of type str.
        image_default (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "image_102": "image_102",
        "image_132": "image_132",
        "image_230": "image_230",
        "image_34": "image_34",
        "image_44": "image_44",
        "image_68": "image_68",
        "image_88": "image_88",
        "image_default": "image_default",
    }

    _optionals = [
        "image_102",
        "image_132",
        "image_230",
        "image_34",
        "image_44",
        "image_68",
        "image_88",
        "image_default",
    ]

    def __init__(
        self,
        image_102=APIHelper.SKIP,
        image_132=APIHelper.SKIP,
        image_230=APIHelper.SKIP,
        image_34=APIHelper.SKIP,
        image_44=APIHelper.SKIP,
        image_68=APIHelper.SKIP,
        image_88=APIHelper.SKIP,
        image_default=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ObjsIcon instance."""
        # Initialize members of the class
        if image_102 is not APIHelper.SKIP:
            self.image_102 = image_102
        if image_132 is not APIHelper.SKIP:
            self.image_132 = image_132
        if image_230 is not APIHelper.SKIP:
            self.image_230 = image_230
        if image_34 is not APIHelper.SKIP:
            self.image_34 = image_34
        if image_44 is not APIHelper.SKIP:
            self.image_44 = image_44
        if image_68 is not APIHelper.SKIP:
            self.image_68 = image_68
        if image_88 is not APIHelper.SKIP:
            self.image_88 = image_88
        if image_default is not APIHelper.SKIP:
            self.image_default = image_default

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        image_102 =\
            dictionary.get("image_102")\
            if dictionary.get("image_102")\
                else APIHelper.SKIP
        image_132 =\
            dictionary.get("image_132")\
            if dictionary.get("image_132")\
                else APIHelper.SKIP
        image_230 =\
            dictionary.get("image_230")\
            if dictionary.get("image_230")\
                else APIHelper.SKIP
        image_34 =\
            dictionary.get("image_34")\
            if dictionary.get("image_34")\
                else APIHelper.SKIP
        image_44 =\
            dictionary.get("image_44")\
            if dictionary.get("image_44")\
                else APIHelper.SKIP
        image_68 =\
            dictionary.get("image_68")\
            if dictionary.get("image_68")\
                else APIHelper.SKIP
        image_88 =\
            dictionary.get("image_88")\
            if dictionary.get("image_88")\
                else APIHelper.SKIP
        image_default =\
            dictionary.get("image_default")\
            if "image_default" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(image_102,
                   image_132,
                   image_230,
                   image_34,
                   image_44,
                   image_68,
                   image_88,
                   image_default,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _image_102=(
            self.image_102
            if hasattr(self, "image_102")
            else None
        )
        _image_132=(
            self.image_132
            if hasattr(self, "image_132")
            else None
        )
        _image_230=(
            self.image_230
            if hasattr(self, "image_230")
            else None
        )
        _image_34=(
            self.image_34
            if hasattr(self, "image_34")
            else None
        )
        _image_44=(
            self.image_44
            if hasattr(self, "image_44")
            else None
        )
        _image_68=(
            self.image_68
            if hasattr(self, "image_68")
            else None
        )
        _image_88=(
            self.image_88
            if hasattr(self, "image_88")
            else None
        )
        _image_default=(
            self.image_default
            if hasattr(self, "image_default")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"image_102={_image_102!r}, "
            f"image_132={_image_132!r}, "
            f"image_230={_image_230!r}, "
            f"image_34={_image_34!r}, "
            f"image_44={_image_44!r}, "
            f"image_68={_image_68!r}, "
            f"image_88={_image_88!r}, "
            f"image_default={_image_default!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _image_102=(
            self.image_102
            if hasattr(self, "image_102")
            else None
        )
        _image_132=(
            self.image_132
            if hasattr(self, "image_132")
            else None
        )
        _image_230=(
            self.image_230
            if hasattr(self, "image_230")
            else None
        )
        _image_34=(
            self.image_34
            if hasattr(self, "image_34")
            else None
        )
        _image_44=(
            self.image_44
            if hasattr(self, "image_44")
            else None
        )
        _image_68=(
            self.image_68
            if hasattr(self, "image_68")
            else None
        )
        _image_88=(
            self.image_88
            if hasattr(self, "image_88")
            else None
        )
        _image_default=(
            self.image_default
            if hasattr(self, "image_default")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"image_102={_image_102!s}, "
            f"image_132={_image_132!s}, "
            f"image_230={_image_230!s}, "
            f"image_34={_image_34!s}, "
            f"image_44={_image_44!s}, "
            f"image_68={_image_68!s}, "
            f"image_88={_image_88!s}, "
            f"image_default={_image_default!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
