"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ObjsEnterpriseUser(object):
    """Implementation of the 'objs_enterprise_user' model.

    Attributes:
        enterprise_id (str): The model property of type str.
        enterprise_name (str): The model property of type str.
        id (str): The model property of type str.
        is_admin (bool): The model property of type bool.
        is_owner (bool): The model property of type bool.
        teams (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "enterprise_id": "enterprise_id",
        "enterprise_name": "enterprise_name",
        "id": "id",
        "is_admin": "is_admin",
        "is_owner": "is_owner",
        "teams": "teams",
    }

    def __init__(
        self,
        enterprise_id=None,
        enterprise_name=None,
        id=None,
        is_admin=None,
        is_owner=None,
        teams=None,
        additional_properties=None):
        """Initialize a ObjsEnterpriseUser instance."""
        # Initialize members of the class
        self.enterprise_id = enterprise_id
        self.enterprise_name = enterprise_name
        self.id = id
        self.is_admin = is_admin
        self.is_owner = is_owner
        self.teams = teams

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        enterprise_id =\
            dictionary.get("enterprise_id")\
            if dictionary.get("enterprise_id")\
                else None
        enterprise_name =\
            dictionary.get("enterprise_name")\
            if dictionary.get("enterprise_name")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        is_admin =\
            dictionary.get("is_admin")\
            if "is_admin" in dictionary.keys()\
                else None
        is_owner =\
            dictionary.get("is_owner")\
            if "is_owner" in dictionary.keys()\
                else None
        teams =\
            dictionary.get("teams")\
            if dictionary.get("teams")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(enterprise_id,
                   enterprise_name,
                   id,
                   is_admin,
                   is_owner,
                   teams,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _enterprise_id=self.enterprise_id
        _enterprise_name=self.enterprise_name
        _id=self.id
        _is_admin=self.is_admin
        _is_owner=self.is_owner
        _teams=self.teams
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"enterprise_id={_enterprise_id!r}, "
            f"enterprise_name={_enterprise_name!r}, "
            f"id={_id!r}, "
            f"is_admin={_is_admin!r}, "
            f"is_owner={_is_owner!r}, "
            f"teams={_teams!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _enterprise_id=self.enterprise_id
        _enterprise_name=self.enterprise_name
        _id=self.id
        _is_admin=self.is_admin
        _is_owner=self.is_owner
        _teams=self.teams
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"enterprise_id={_enterprise_id!s}, "
            f"enterprise_name={_enterprise_name!s}, "
            f"id={_id!s}, "
            f"is_admin={_is_admin!s}, "
            f"is_owner={_is_owner!s}, "
            f"teams={_teams!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
