"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ObjsPrimaryOwner(object):
    """Implementation of the 'objs_primary_owner' model.

    Attributes:
        email (str): The model property of type str.
        id (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": "email",
        "id": "id",
    }

    def __init__(
        self,
        email=None,
        id=None,
        additional_properties=None):
        """Initialize a ObjsPrimaryOwner instance."""
        # Initialize members of the class
        self.email = email
        self.id = id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(email,
                   id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _email=self.email
        _id=self.id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!r}, "
            f"id={_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _email=self.email
        _id=self.id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!s}, "
            f"id={_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
