"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class PagingObject(object):
    """Implementation of the 'paging object' model.

    Attributes:
        count (int): The model property of type int.
        page (int): The model property of type int.
        pages (int): The model property of type int.
        per_page (int): The model property of type int.
        spill (int): The model property of type int.
        total (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page": "page",
        "total": "total",
        "count": "count",
        "pages": "pages",
        "per_page": "per_page",
        "spill": "spill",
    }

    _optionals = [
        "count",
        "pages",
        "per_page",
        "spill",
    ]

    def __init__(
        self,
        page=None,
        total=None,
        count=APIHelper.SKIP,
        pages=APIHelper.SKIP,
        per_page=APIHelper.SKIP,
        spill=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PagingObject instance."""
        # Initialize members of the class
        if count is not APIHelper.SKIP:
            self.count = count
        self.page = page
        if pages is not APIHelper.SKIP:
            self.pages = pages
        if per_page is not APIHelper.SKIP:
            self.per_page = per_page
        if spill is not APIHelper.SKIP:
            self.spill = spill
        self.total = total

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        page =\
            dictionary.get("page")\
            if dictionary.get("page")\
                else None
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else None
        count =\
            dictionary.get("count")\
            if dictionary.get("count")\
                else APIHelper.SKIP
        pages =\
            dictionary.get("pages")\
            if dictionary.get("pages")\
                else APIHelper.SKIP
        per_page =\
            dictionary.get("per_page")\
            if dictionary.get("per_page")\
                else APIHelper.SKIP
        spill =\
            dictionary.get("spill")\
            if dictionary.get("spill")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(page,
                   total,
                   count,
                   pages,
                   per_page,
                   spill,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _page=self.page
        _pages=(
            self.pages
            if hasattr(self, "pages")
            else None
        )
        _per_page=(
            self.per_page
            if hasattr(self, "per_page")
            else None
        )
        _spill=(
            self.spill
            if hasattr(self, "spill")
            else None
        )
        _total=self.total
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"count={_count!r}, "
            f"page={_page!r}, "
            f"pages={_pages!r}, "
            f"per_page={_per_page!r}, "
            f"spill={_spill!r}, "
            f"total={_total!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _count=(
            self.count
            if hasattr(self, "count")
            else None
        )
        _page=self.page
        _pages=(
            self.pages
            if hasattr(self, "pages")
            else None
        )
        _per_page=(
            self.per_page
            if hasattr(self, "per_page")
            else None
        )
        _spill=(
            self.spill
            if hasattr(self, "spill")
            else None
        )
        _total=self.total
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"count={_count!s}, "
            f"page={_page!s}, "
            f"pages={_pages!s}, "
            f"per_page={_per_page!s}, "
            f"spill={_spill!s}, "
            f"total={_total!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
