"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class Prefs(object):
    """Implementation of the 'Prefs' model.

    Attributes:
        channels (List[str]): The model property of type List[str].
        groups (List[str]): The model property of type List[str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "channels": "channels",
        "groups": "groups",
    }

    def __init__(
        self,
        channels=None,
        groups=None,
        additional_properties=None):
        """Initialize a Prefs instance."""
        # Initialize members of the class
        self.channels = channels
        self.groups = groups

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        channels =\
            dictionary.get("channels")\
            if dictionary.get("channels")\
                else None
        groups =\
            dictionary.get("groups")\
            if dictionary.get("groups")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(channels,
                   groups,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _channels=self.channels
        _groups=self.groups
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channels={_channels!r}, "
            f"groups={_groups!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _channels=self.channels
        _groups=self.groups
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"channels={_channels!s}, "
            f"groups={_groups!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
