"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class Purpose(object):
    """Implementation of the 'Purpose' model.

    Attributes:
        creator (str): The model property of type str.
        last_set (int): The model property of type int.
        value (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "creator": "creator",
        "last_set": "last_set",
        "value": "value",
    }

    def __init__(
        self,
        creator=None,
        last_set=None,
        value=None,
        additional_properties=None):
        """Initialize a Purpose instance."""
        # Initialize members of the class
        self.creator = creator
        self.last_set = last_set
        self.value = value

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        creator =\
            dictionary.get("creator")\
            if dictionary.get("creator")\
                else None
        last_set =\
            dictionary.get("last_set")\
            if dictionary.get("last_set")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(creator,
                   last_set,
                   value,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _creator=self.creator
        _last_set=self.last_set
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"creator={_creator!r}, "
            f"last_set={_last_set!r}, "
            f"value={_value!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _creator=self.creator
        _last_set=self.last_set
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"creator={_creator!s}, "
            f"last_set={_last_set!s}, "
            f"value={_value!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
