"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.objs_reminder import (
    ObjsReminder,
)


class RemindersAddSchema(object):
    """Implementation of the 'reminders.add schema' model.

    Schema for successful response from reminders.add method

    Attributes:
        ok (str): The model property of type str.
        reminder (ObjsReminder): The model property of type ObjsReminder.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "reminder": "reminder",
    }

    def __init__(
        self,
        reminder=None,
        additional_properties=None):
        """Initialize a RemindersAddSchema instance."""
        # Initialize members of the class
        self.ok = "True"
        self.reminder = reminder

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        reminder =\
            ObjsReminder.from_dictionary(
                dictionary.get("reminder"))\
                if dictionary.get("reminder") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(reminder,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ok=self.ok
        _reminder=self.reminder
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!r}, "
            f"reminder={_reminder!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ok=self.ok
        _reminder=self.reminder
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!s}, "
            f"reminder={_reminder!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
