"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class ResourcesInInfoFromAppsPermissionsInfo(object):
    """Implementation of the 'resources in info from apps.permissions.info' model.

    Attributes:
        excluded_ids (List[Any]): The model property of type List[Any].
        ids (List[Any]): The model property of type List[Any].
        wildcard (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ids": "ids",
        "excluded_ids": "excluded_ids",
        "wildcard": "wildcard",
    }

    _optionals = [
        "excluded_ids",
        "wildcard",
    ]

    def __init__(
        self,
        ids=None,
        excluded_ids=APIHelper.SKIP,
        wildcard=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ResourcesInInfoFromAppsPermissionsInfo instance."""
        # Initialize members of the class
        if excluded_ids is not APIHelper.SKIP:
            self.excluded_ids = excluded_ids
        self.ids = ids
        if wildcard is not APIHelper.SKIP:
            self.wildcard = wildcard

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ids =\
            dictionary.get("ids")\
            if dictionary.get("ids")\
                else None
        excluded_ids =\
            dictionary.get("excluded_ids")\
            if dictionary.get("excluded_ids")\
                else APIHelper.SKIP
        wildcard =\
            dictionary.get("wildcard")\
            if "wildcard" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ids,
                   excluded_ids,
                   wildcard,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _excluded_ids=(
            self.excluded_ids
            if hasattr(self, "excluded_ids")
            else None
        )
        _ids=self.ids
        _wildcard=(
            self.wildcard
            if hasattr(self, "wildcard")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"excluded_ids={_excluded_ids!r}, "
            f"ids={_ids!r}, "
            f"wildcard={_wildcard!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _excluded_ids=(
            self.excluded_ids
            if hasattr(self, "excluded_ids")
            else None
        )
        _ids=self.ids
        _wildcard=(
            self.wildcard
            if hasattr(self, "wildcard")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"excluded_ids={_excluded_ids!s}, "
            f"ids={_ids!s}, "
            f"wildcard={_wildcard!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
