"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.mself import Self
from slackwebapi.models.team_1 import Team1


class RtmConnectSchema(object):
    """Implementation of the 'rtm.connect schema' model.

    Schema for successful response from rtm.connect method

    Attributes:
        ok (str): The model property of type str.
        mself (Self): The model property of type Self.
        team (Team1): The model property of type Team1.
        url (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "mself": "self",
        "team": "team",
        "url": "url",
    }

    def __init__(
        self,
        mself=None,
        team=None,
        url=None,
        additional_properties=None):
        """Initialize a RtmConnectSchema instance."""
        # Initialize members of the class
        self.ok = "True"
        self.mself = mself
        self.team = team
        self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mself =\
            Self.from_dictionary(
                dictionary.get("self"))\
                if dictionary.get("self") else None
        team =\
            Team1.from_dictionary(
                dictionary.get("team"))\
                if dictionary.get("team") else None
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mself,
                   team,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ok=self.ok
        _mself=self.mself
        _team=self.team
        _url=self.url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!r}, "
            f"mself={_mself!r}, "
            f"team={_team!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ok=self.ok
        _mself=self.mself
        _team=self.team
        _url=self.url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!s}, "
            f"mself={_mself!s}, "
            f"team={_team!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
