"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.paging_object import (
    PagingObject,
)


class StarsListSchema(object):
    """Implementation of the 'stars.list schema' model.

    Schema for successful response from stars.list method

    Attributes:
        items (List[Any]): The model property of type List[Any].
        ok (str): The model property of type str.
        paging (PagingObject): The model property of type PagingObject.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "items": "items",
        "ok": "ok",
        "paging": "paging",
    }

    _optionals = [
        "paging",
    ]

    def __init__(
        self,
        items=None,
        paging=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a StarsListSchema instance."""
        # Initialize members of the class
        self.items = items
        self.ok = "True"
        if paging is not APIHelper.SKIP:
            self.paging = paging

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        items =\
            dictionary.get("items")\
            if dictionary.get("items")\
                else None
        paging =\
            PagingObject.from_dictionary(
                dictionary.get("paging"))\
                if "paging" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(items,
                   paging,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _items=self.items
        _ok=self.ok
        _paging=(
            self.paging
            if hasattr(self, "paging")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"items={_items!r}, "
            f"ok={_ok!r}, "
            f"paging={_paging!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _items=self.items
        _ok=self.ok
        _paging=(
            self.paging
            if hasattr(self, "paging")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"items={_items!s}, "
            f"ok={_ok!s}, "
            f"paging={_paging!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
