"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.login import Login
from slackwebapi.models.paging_object import (
    PagingObject,
)


class TeamAccessLogsSchema(object):
    """Implementation of the 'team.accessLogs schema' model.

    Schema for successful response from team.accessLogs method

    Attributes:
        logins (List[Login]): The model property of type List[Login].
        ok (str): The model property of type str.
        paging (PagingObject): The model property of type PagingObject.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "logins": "logins",
        "ok": "ok",
        "paging": "paging",
    }

    def __init__(
        self,
        logins=None,
        paging=None,
        additional_properties=None):
        """Initialize a TeamAccessLogsSchema instance."""
        # Initialize members of the class
        self.logins = logins
        self.ok = "True"
        self.paging = paging

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        logins = None
        if dictionary.get("logins") is not None:
            logins = [
                Login.from_dictionary(x)
                    for x in dictionary.get("logins")
            ]
        paging =\
            PagingObject.from_dictionary(
                dictionary.get("paging"))\
                if dictionary.get("paging") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(logins,
                   paging,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _logins=self.logins
        _ok=self.ok
        _paging=self.paging
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"logins={_logins!r}, "
            f"ok={_ok!r}, "
            f"paging={_paging!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _logins=self.logins
        _ok=self.ok
        _paging=self.paging
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"logins={_logins!s}, "
            f"ok={_ok!s}, "
            f"paging={_paging!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
