"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class Team1(object):
    """Implementation of the 'Team1' model.

    Attributes:
        domain (str): The model property of type str.
        id (str): The model property of type str.
        name (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "domain": "domain",
        "id": "id",
        "name": "name",
    }

    def __init__(
        self,
        domain=None,
        id=None,
        name=None,
        additional_properties=None):
        """Initialize a Team1 instance."""
        # Initialize members of the class
        self.domain = domain
        self.id = id
        self.name = name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        domain =\
            dictionary.get("domain")\
            if dictionary.get("domain")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else None
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(domain,
                   id,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _domain=self.domain
        _id=self.id
        _name=self.name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"domain={_domain!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _domain=self.domain
        _id=self.id
        _name=self.name
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"domain={_domain!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
