"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.subteam_usergroup_object import (
    SubteamUsergroupObject,
)


class UsergroupsDisableSchema(object):
    """Implementation of the 'usergroups.disable schema' model.

    Schema for successful response from usergroups.disable method

    Attributes:
        ok (str): The model property of type str.
        usergroup (SubteamUsergroupObject): The model property of type
            SubteamUsergroupObject.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "usergroup": "usergroup",
    }

    def __init__(
        self,
        usergroup=None,
        additional_properties=None):
        """Initialize a UsergroupsDisableSchema instance."""
        # Initialize members of the class
        self.ok = "True"
        self.usergroup = usergroup

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        usergroup =\
            SubteamUsergroupObject.from_dictionary(
                dictionary.get("usergroup"))\
                if dictionary.get("usergroup") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(usergroup,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ok=self.ok
        _usergroup=self.usergroup
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!r}, "
            f"usergroup={_usergroup!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ok=self.ok
        _usergroup=self.usergroup
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ok={_ok!s}, "
            f"usergroup={_usergroup!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
