"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper


class UserProfileObject(object):
    """Implementation of the 'User profile object' model.

    Attributes:
        always_active (bool): The model property of type bool.
        api_app_id (str): The model property of type str.
        avatar_hash (str): The model property of type str.
        bot_id (str): The model property of type str.
        display_name (str): The model property of type str.
        display_name_normalized (str): The model property of type str.
        email (str): The model property of type str.
        fields (List[Any]): The model property of type List[Any].
        first_name (str): The model property of type str.
        guest_expiration_ts (int): The model property of type int.
        guest_invited_by (str): The model property of type str.
        image_1024 (str): The model property of type str.
        image_192 (str): The model property of type str.
        image_24 (str): The model property of type str.
        image_32 (str): The model property of type str.
        image_48 (str): The model property of type str.
        image_512 (str): The model property of type str.
        image_72 (str): The model property of type str.
        image_original (str): The model property of type str.
        is_app_user (bool): The model property of type bool.
        is_custom_image (bool): The model property of type bool.
        is_restricted (bool): The model property of type bool.
        is_ultra_restricted (bool): The model property of type bool.
        last_avatar_image_hash (str): The model property of type str.
        last_name (str): The model property of type str.
        memberships_count (int): The model property of type int.
        name (str): The model property of type str.
        phone (str): The model property of type str.
        pronouns (str): The model property of type str.
        real_name (str): The model property of type str.
        real_name_normalized (str): The model property of type str.
        skype (str): The model property of type str.
        status_default_emoji (str): The model property of type str.
        status_default_text (str): The model property of type str.
        status_default_text_canonical (str): The model property of type str.
        status_emoji (str): The model property of type str.
        status_expiration (int): The model property of type int.
        status_text (str): The model property of type str.
        status_text_canonical (str): The model property of type str.
        team (str): The model property of type str.
        title (str): The model property of type str.
        updated (int): The model property of type int.
        user_id (str): The model property of type str.
        username (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "avatar_hash": "avatar_hash",
        "display_name": "display_name",
        "display_name_normalized": "display_name_normalized",
        "fields": "fields",
        "phone": "phone",
        "real_name": "real_name",
        "real_name_normalized": "real_name_normalized",
        "skype": "skype",
        "status_emoji": "status_emoji",
        "status_text": "status_text",
        "title": "title",
        "always_active": "always_active",
        "api_app_id": "api_app_id",
        "bot_id": "bot_id",
        "email": "email",
        "first_name": "first_name",
        "guest_expiration_ts": "guest_expiration_ts",
        "guest_invited_by": "guest_invited_by",
        "image_1024": "image_1024",
        "image_192": "image_192",
        "image_24": "image_24",
        "image_32": "image_32",
        "image_48": "image_48",
        "image_512": "image_512",
        "image_72": "image_72",
        "image_original": "image_original",
        "is_app_user": "is_app_user",
        "is_custom_image": "is_custom_image",
        "is_restricted": "is_restricted",
        "is_ultra_restricted": "is_ultra_restricted",
        "last_avatar_image_hash": "last_avatar_image_hash",
        "last_name": "last_name",
        "memberships_count": "memberships_count",
        "name": "name",
        "pronouns": "pronouns",
        "status_default_emoji": "status_default_emoji",
        "status_default_text": "status_default_text",
        "status_default_text_canonical": "status_default_text_canonical",
        "status_expiration": "status_expiration",
        "status_text_canonical": "status_text_canonical",
        "team": "team",
        "updated": "updated",
        "user_id": "user_id",
        "username": "username",
    }

    _optionals = [
        "always_active",
        "api_app_id",
        "bot_id",
        "email",
        "first_name",
        "guest_expiration_ts",
        "guest_invited_by",
        "image_1024",
        "image_192",
        "image_24",
        "image_32",
        "image_48",
        "image_512",
        "image_72",
        "image_original",
        "is_app_user",
        "is_custom_image",
        "is_restricted",
        "is_ultra_restricted",
        "last_avatar_image_hash",
        "last_name",
        "memberships_count",
        "name",
        "pronouns",
        "status_default_emoji",
        "status_default_text",
        "status_default_text_canonical",
        "status_expiration",
        "status_text_canonical",
        "team",
        "updated",
        "user_id",
        "username",
    ]

    _nullables = [
        "email",
        "fields",
        "first_name",
        "guest_expiration_ts",
        "guest_invited_by",
        "image_1024",
        "image_192",
        "image_24",
        "image_32",
        "image_48",
        "image_512",
        "image_72",
        "image_original",
        "is_restricted",
        "is_ultra_restricted",
        "last_name",
        "name",
        "status_default_text_canonical",
        "status_text_canonical",
        "username",
    ]

    def __init__(
        self,
        avatar_hash=None,
        display_name=None,
        display_name_normalized=None,
        fields=None,
        phone=None,
        real_name=None,
        real_name_normalized=None,
        skype=None,
        status_emoji=None,
        status_text=None,
        title=None,
        always_active=APIHelper.SKIP,
        api_app_id=APIHelper.SKIP,
        bot_id=APIHelper.SKIP,
        email=APIHelper.SKIP,
        first_name=APIHelper.SKIP,
        guest_expiration_ts=APIHelper.SKIP,
        guest_invited_by=APIHelper.SKIP,
        image_1024=APIHelper.SKIP,
        image_192=APIHelper.SKIP,
        image_24=APIHelper.SKIP,
        image_32=APIHelper.SKIP,
        image_48=APIHelper.SKIP,
        image_512=APIHelper.SKIP,
        image_72=APIHelper.SKIP,
        image_original=APIHelper.SKIP,
        is_app_user=APIHelper.SKIP,
        is_custom_image=APIHelper.SKIP,
        is_restricted=APIHelper.SKIP,
        is_ultra_restricted=APIHelper.SKIP,
        last_avatar_image_hash=APIHelper.SKIP,
        last_name=APIHelper.SKIP,
        memberships_count=APIHelper.SKIP,
        name=APIHelper.SKIP,
        pronouns=APIHelper.SKIP,
        status_default_emoji=APIHelper.SKIP,
        status_default_text=APIHelper.SKIP,
        status_default_text_canonical=APIHelper.SKIP,
        status_expiration=APIHelper.SKIP,
        status_text_canonical=APIHelper.SKIP,
        team=APIHelper.SKIP,
        updated=APIHelper.SKIP,
        user_id=APIHelper.SKIP,
        username=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UserProfileObject instance."""
        # Initialize members of the class
        if always_active is not APIHelper.SKIP:
            self.always_active = always_active
        if api_app_id is not APIHelper.SKIP:
            self.api_app_id = api_app_id
        self.avatar_hash = avatar_hash
        if bot_id is not APIHelper.SKIP:
            self.bot_id = bot_id
        self.display_name = display_name
        self.display_name_normalized = display_name_normalized
        if email is not APIHelper.SKIP:
            self.email = email
        self.fields = fields
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name
        if guest_expiration_ts is not APIHelper.SKIP:
            self.guest_expiration_ts = guest_expiration_ts
        if guest_invited_by is not APIHelper.SKIP:
            self.guest_invited_by = guest_invited_by
        if image_1024 is not APIHelper.SKIP:
            self.image_1024 = image_1024
        if image_192 is not APIHelper.SKIP:
            self.image_192 = image_192
        if image_24 is not APIHelper.SKIP:
            self.image_24 = image_24
        if image_32 is not APIHelper.SKIP:
            self.image_32 = image_32
        if image_48 is not APIHelper.SKIP:
            self.image_48 = image_48
        if image_512 is not APIHelper.SKIP:
            self.image_512 = image_512
        if image_72 is not APIHelper.SKIP:
            self.image_72 = image_72
        if image_original is not APIHelper.SKIP:
            self.image_original = image_original
        if is_app_user is not APIHelper.SKIP:
            self.is_app_user = is_app_user
        if is_custom_image is not APIHelper.SKIP:
            self.is_custom_image = is_custom_image
        if is_restricted is not APIHelper.SKIP:
            self.is_restricted = is_restricted
        if is_ultra_restricted is not APIHelper.SKIP:
            self.is_ultra_restricted = is_ultra_restricted
        if last_avatar_image_hash is not APIHelper.SKIP:
            self.last_avatar_image_hash = last_avatar_image_hash
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name
        if memberships_count is not APIHelper.SKIP:
            self.memberships_count = memberships_count
        if name is not APIHelper.SKIP:
            self.name = name
        self.phone = phone
        if pronouns is not APIHelper.SKIP:
            self.pronouns = pronouns
        self.real_name = real_name
        self.real_name_normalized = real_name_normalized
        self.skype = skype
        if status_default_emoji is not APIHelper.SKIP:
            self.status_default_emoji = status_default_emoji
        if status_default_text is not APIHelper.SKIP:
            self.status_default_text = status_default_text
        if status_default_text_canonical is not APIHelper.SKIP:
            self.status_default_text_canonical = status_default_text_canonical
        self.status_emoji = status_emoji
        if status_expiration is not APIHelper.SKIP:
            self.status_expiration = status_expiration
        self.status_text = status_text
        if status_text_canonical is not APIHelper.SKIP:
            self.status_text_canonical = status_text_canonical
        if team is not APIHelper.SKIP:
            self.team = team
        self.title = title
        if updated is not APIHelper.SKIP:
            self.updated = updated
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if username is not APIHelper.SKIP:
            self.username = username

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        avatar_hash =\
            dictionary.get("avatar_hash")\
            if dictionary.get("avatar_hash")\
                else None
        display_name =\
            dictionary.get("display_name")\
            if dictionary.get("display_name")\
                else None
        display_name_normalized =\
            dictionary.get("display_name_normalized")\
            if dictionary.get("display_name_normalized")\
                else None
        fields =\
            dictionary.get("fields")\
            if dictionary.get("fields")\
                else None
        phone =\
            dictionary.get("phone")\
            if dictionary.get("phone")\
                else None
        real_name =\
            dictionary.get("real_name")\
            if dictionary.get("real_name")\
                else None
        real_name_normalized =\
            dictionary.get("real_name_normalized")\
            if dictionary.get("real_name_normalized")\
                else None
        skype =\
            dictionary.get("skype")\
            if dictionary.get("skype")\
                else None
        status_emoji =\
            dictionary.get("status_emoji")\
            if dictionary.get("status_emoji")\
                else None
        status_text =\
            dictionary.get("status_text")\
            if dictionary.get("status_text")\
                else None
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else None
        always_active =\
            dictionary.get("always_active")\
            if "always_active" in dictionary.keys()\
                else APIHelper.SKIP
        api_app_id =\
            dictionary.get("api_app_id")\
            if dictionary.get("api_app_id")\
                else APIHelper.SKIP
        bot_id =\
            dictionary.get("bot_id")\
            if dictionary.get("bot_id")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if "email" in dictionary.keys()\
                else APIHelper.SKIP
        first_name =\
            dictionary.get("first_name")\
            if "first_name" in dictionary.keys()\
                else APIHelper.SKIP
        guest_expiration_ts =\
            dictionary.get("guest_expiration_ts")\
            if "guest_expiration_ts" in dictionary.keys()\
                else APIHelper.SKIP
        guest_invited_by =\
            dictionary.get("guest_invited_by")\
            if "guest_invited_by" in dictionary.keys()\
                else APIHelper.SKIP
        image_1024 =\
            dictionary.get("image_1024")\
            if "image_1024" in dictionary.keys()\
                else APIHelper.SKIP
        image_192 =\
            dictionary.get("image_192")\
            if "image_192" in dictionary.keys()\
                else APIHelper.SKIP
        image_24 =\
            dictionary.get("image_24")\
            if "image_24" in dictionary.keys()\
                else APIHelper.SKIP
        image_32 =\
            dictionary.get("image_32")\
            if "image_32" in dictionary.keys()\
                else APIHelper.SKIP
        image_48 =\
            dictionary.get("image_48")\
            if "image_48" in dictionary.keys()\
                else APIHelper.SKIP
        image_512 =\
            dictionary.get("image_512")\
            if "image_512" in dictionary.keys()\
                else APIHelper.SKIP
        image_72 =\
            dictionary.get("image_72")\
            if "image_72" in dictionary.keys()\
                else APIHelper.SKIP
        image_original =\
            dictionary.get("image_original")\
            if "image_original" in dictionary.keys()\
                else APIHelper.SKIP
        is_app_user =\
            dictionary.get("is_app_user")\
            if "is_app_user" in dictionary.keys()\
                else APIHelper.SKIP
        is_custom_image =\
            dictionary.get("is_custom_image")\
            if "is_custom_image" in dictionary.keys()\
                else APIHelper.SKIP
        is_restricted =\
            dictionary.get("is_restricted")\
            if "is_restricted" in dictionary.keys()\
                else APIHelper.SKIP
        is_ultra_restricted =\
            dictionary.get("is_ultra_restricted")\
            if "is_ultra_restricted" in dictionary.keys()\
                else APIHelper.SKIP
        last_avatar_image_hash =\
            dictionary.get("last_avatar_image_hash")\
            if dictionary.get("last_avatar_image_hash")\
                else APIHelper.SKIP
        last_name =\
            dictionary.get("last_name")\
            if "last_name" in dictionary.keys()\
                else APIHelper.SKIP
        memberships_count =\
            dictionary.get("memberships_count")\
            if dictionary.get("memberships_count")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if "name" in dictionary.keys()\
                else APIHelper.SKIP
        pronouns =\
            dictionary.get("pronouns")\
            if dictionary.get("pronouns")\
                else APIHelper.SKIP
        status_default_emoji =\
            dictionary.get("status_default_emoji")\
            if dictionary.get("status_default_emoji")\
                else APIHelper.SKIP
        status_default_text =\
            dictionary.get("status_default_text")\
            if dictionary.get("status_default_text")\
                else APIHelper.SKIP
        status_default_text_canonical =\
            dictionary.get("status_default_text_canonical")\
            if "status_default_text_canonical" in dictionary.keys()\
                else APIHelper.SKIP
        status_expiration =\
            dictionary.get("status_expiration")\
            if dictionary.get("status_expiration")\
                else APIHelper.SKIP
        status_text_canonical =\
            dictionary.get("status_text_canonical")\
            if "status_text_canonical" in dictionary.keys()\
                else APIHelper.SKIP
        team =\
            dictionary.get("team")\
            if dictionary.get("team")\
                else APIHelper.SKIP
        updated =\
            dictionary.get("updated")\
            if dictionary.get("updated")\
                else APIHelper.SKIP
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if "username" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(avatar_hash,
                   display_name,
                   display_name_normalized,
                   fields,
                   phone,
                   real_name,
                   real_name_normalized,
                   skype,
                   status_emoji,
                   status_text,
                   title,
                   always_active,
                   api_app_id,
                   bot_id,
                   email,
                   first_name,
                   guest_expiration_ts,
                   guest_invited_by,
                   image_1024,
                   image_192,
                   image_24,
                   image_32,
                   image_48,
                   image_512,
                   image_72,
                   image_original,
                   is_app_user,
                   is_custom_image,
                   is_restricted,
                   is_ultra_restricted,
                   last_avatar_image_hash,
                   last_name,
                   memberships_count,
                   name,
                   pronouns,
                   status_default_emoji,
                   status_default_text,
                   status_default_text_canonical,
                   status_expiration,
                   status_text_canonical,
                   team,
                   updated,
                   user_id,
                   username,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _always_active=(
            self.always_active
            if hasattr(self, "always_active")
            else None
        )
        _api_app_id=(
            self.api_app_id
            if hasattr(self, "api_app_id")
            else None
        )
        _avatar_hash=self.avatar_hash
        _bot_id=(
            self.bot_id
            if hasattr(self, "bot_id")
            else None
        )
        _display_name=self.display_name
        _display_name_normalized=self.display_name_normalized
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _fields=self.fields
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _guest_expiration_ts=(
            self.guest_expiration_ts
            if hasattr(self, "guest_expiration_ts")
            else None
        )
        _guest_invited_by=(
            self.guest_invited_by
            if hasattr(self, "guest_invited_by")
            else None
        )
        _image_1024=(
            self.image_1024
            if hasattr(self, "image_1024")
            else None
        )
        _image_192=(
            self.image_192
            if hasattr(self, "image_192")
            else None
        )
        _image_24=(
            self.image_24
            if hasattr(self, "image_24")
            else None
        )
        _image_32=(
            self.image_32
            if hasattr(self, "image_32")
            else None
        )
        _image_48=(
            self.image_48
            if hasattr(self, "image_48")
            else None
        )
        _image_512=(
            self.image_512
            if hasattr(self, "image_512")
            else None
        )
        _image_72=(
            self.image_72
            if hasattr(self, "image_72")
            else None
        )
        _image_original=(
            self.image_original
            if hasattr(self, "image_original")
            else None
        )
        _is_app_user=(
            self.is_app_user
            if hasattr(self, "is_app_user")
            else None
        )
        _is_custom_image=(
            self.is_custom_image
            if hasattr(self, "is_custom_image")
            else None
        )
        _is_restricted=(
            self.is_restricted
            if hasattr(self, "is_restricted")
            else None
        )
        _is_ultra_restricted=(
            self.is_ultra_restricted
            if hasattr(self, "is_ultra_restricted")
            else None
        )
        _last_avatar_image_hash=(
            self.last_avatar_image_hash
            if hasattr(self, "last_avatar_image_hash")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _memberships_count=(
            self.memberships_count
            if hasattr(self, "memberships_count")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _phone=self.phone
        _pronouns=(
            self.pronouns
            if hasattr(self, "pronouns")
            else None
        )
        _real_name=self.real_name
        _real_name_normalized=self.real_name_normalized
        _skype=self.skype
        _status_default_emoji=(
            self.status_default_emoji
            if hasattr(self, "status_default_emoji")
            else None
        )
        _status_default_text=(
            self.status_default_text
            if hasattr(self, "status_default_text")
            else None
        )
        _status_default_text_canonical=(
            self.status_default_text_canonical
            if hasattr(self, "status_default_text_canonical")
            else None
        )
        _status_emoji=self.status_emoji
        _status_expiration=(
            self.status_expiration
            if hasattr(self, "status_expiration")
            else None
        )
        _status_text=self.status_text
        _status_text_canonical=(
            self.status_text_canonical
            if hasattr(self, "status_text_canonical")
            else None
        )
        _team=(
            self.team
            if hasattr(self, "team")
            else None
        )
        _title=self.title
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"always_active={_always_active!r}, "
            f"api_app_id={_api_app_id!r}, "
            f"avatar_hash={_avatar_hash!r}, "
            f"bot_id={_bot_id!r}, "
            f"display_name={_display_name!r}, "
            f"display_name_normalized={_display_name_normalized!r}, "
            f"email={_email!r}, "
            f"fields={_fields!r}, "
            f"first_name={_first_name!r}, "
            f"guest_expiration_ts={_guest_expiration_ts!r}, "
            f"guest_invited_by={_guest_invited_by!r}, "
            f"image_1024={_image_1024!r}, "
            f"image_192={_image_192!r}, "
            f"image_24={_image_24!r}, "
            f"image_32={_image_32!r}, "
            f"image_48={_image_48!r}, "
            f"image_512={_image_512!r}, "
            f"image_72={_image_72!r}, "
            f"image_original={_image_original!r}, "
            f"is_app_user={_is_app_user!r}, "
            f"is_custom_image={_is_custom_image!r}, "
            f"is_restricted={_is_restricted!r}, "
            f"is_ultra_restricted={_is_ultra_restricted!r}, "
            f"last_avatar_image_hash={_last_avatar_image_hash!r}, "
            f"last_name={_last_name!r}, "
            f"memberships_count={_memberships_count!r}, "
            f"name={_name!r}, "
            f"phone={_phone!r}, "
            f"pronouns={_pronouns!r}, "
            f"real_name={_real_name!r}, "
            f"real_name_normalized={_real_name_normalized!r}, "
            f"skype={_skype!r}, "
            f"status_default_emoji={_status_default_emoji!r}, "
            f"status_default_text={_status_default_text!r}, "
            f"status_default_text_canonical={_status_default_text_canonical!r}, "
            f"status_emoji={_status_emoji!r}, "
            f"status_expiration={_status_expiration!r}, "
            f"status_text={_status_text!r}, "
            f"status_text_canonical={_status_text_canonical!r}, "
            f"team={_team!r}, "
            f"title={_title!r}, "
            f"updated={_updated!r}, "
            f"user_id={_user_id!r}, "
            f"username={_username!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _always_active=(
            self.always_active
            if hasattr(self, "always_active")
            else None
        )
        _api_app_id=(
            self.api_app_id
            if hasattr(self, "api_app_id")
            else None
        )
        _avatar_hash=self.avatar_hash
        _bot_id=(
            self.bot_id
            if hasattr(self, "bot_id")
            else None
        )
        _display_name=self.display_name
        _display_name_normalized=self.display_name_normalized
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _fields=self.fields
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _guest_expiration_ts=(
            self.guest_expiration_ts
            if hasattr(self, "guest_expiration_ts")
            else None
        )
        _guest_invited_by=(
            self.guest_invited_by
            if hasattr(self, "guest_invited_by")
            else None
        )
        _image_1024=(
            self.image_1024
            if hasattr(self, "image_1024")
            else None
        )
        _image_192=(
            self.image_192
            if hasattr(self, "image_192")
            else None
        )
        _image_24=(
            self.image_24
            if hasattr(self, "image_24")
            else None
        )
        _image_32=(
            self.image_32
            if hasattr(self, "image_32")
            else None
        )
        _image_48=(
            self.image_48
            if hasattr(self, "image_48")
            else None
        )
        _image_512=(
            self.image_512
            if hasattr(self, "image_512")
            else None
        )
        _image_72=(
            self.image_72
            if hasattr(self, "image_72")
            else None
        )
        _image_original=(
            self.image_original
            if hasattr(self, "image_original")
            else None
        )
        _is_app_user=(
            self.is_app_user
            if hasattr(self, "is_app_user")
            else None
        )
        _is_custom_image=(
            self.is_custom_image
            if hasattr(self, "is_custom_image")
            else None
        )
        _is_restricted=(
            self.is_restricted
            if hasattr(self, "is_restricted")
            else None
        )
        _is_ultra_restricted=(
            self.is_ultra_restricted
            if hasattr(self, "is_ultra_restricted")
            else None
        )
        _last_avatar_image_hash=(
            self.last_avatar_image_hash
            if hasattr(self, "last_avatar_image_hash")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _memberships_count=(
            self.memberships_count
            if hasattr(self, "memberships_count")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _phone=self.phone
        _pronouns=(
            self.pronouns
            if hasattr(self, "pronouns")
            else None
        )
        _real_name=self.real_name
        _real_name_normalized=self.real_name_normalized
        _skype=self.skype
        _status_default_emoji=(
            self.status_default_emoji
            if hasattr(self, "status_default_emoji")
            else None
        )
        _status_default_text=(
            self.status_default_text
            if hasattr(self, "status_default_text")
            else None
        )
        _status_default_text_canonical=(
            self.status_default_text_canonical
            if hasattr(self, "status_default_text_canonical")
            else None
        )
        _status_emoji=self.status_emoji
        _status_expiration=(
            self.status_expiration
            if hasattr(self, "status_expiration")
            else None
        )
        _status_text=self.status_text
        _status_text_canonical=(
            self.status_text_canonical
            if hasattr(self, "status_text_canonical")
            else None
        )
        _team=(
            self.team
            if hasattr(self, "team")
            else None
        )
        _title=self.title
        _updated=(
            self.updated
            if hasattr(self, "updated")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"always_active={_always_active!s}, "
            f"api_app_id={_api_app_id!s}, "
            f"avatar_hash={_avatar_hash!s}, "
            f"bot_id={_bot_id!s}, "
            f"display_name={_display_name!s}, "
            f"display_name_normalized={_display_name_normalized!s}, "
            f"email={_email!s}, "
            f"fields={_fields!s}, "
            f"first_name={_first_name!s}, "
            f"guest_expiration_ts={_guest_expiration_ts!s}, "
            f"guest_invited_by={_guest_invited_by!s}, "
            f"image_1024={_image_1024!s}, "
            f"image_192={_image_192!s}, "
            f"image_24={_image_24!s}, "
            f"image_32={_image_32!s}, "
            f"image_48={_image_48!s}, "
            f"image_512={_image_512!s}, "
            f"image_72={_image_72!s}, "
            f"image_original={_image_original!s}, "
            f"is_app_user={_is_app_user!s}, "
            f"is_custom_image={_is_custom_image!s}, "
            f"is_restricted={_is_restricted!s}, "
            f"is_ultra_restricted={_is_ultra_restricted!s}, "
            f"last_avatar_image_hash={_last_avatar_image_hash!s}, "
            f"last_name={_last_name!s}, "
            f"memberships_count={_memberships_count!s}, "
            f"name={_name!s}, "
            f"phone={_phone!s}, "
            f"pronouns={_pronouns!s}, "
            f"real_name={_real_name!s}, "
            f"real_name_normalized={_real_name_normalized!s}, "
            f"skype={_skype!s}, "
            f"status_default_emoji={_status_default_emoji!s}, "
            f"status_default_text={_status_default_text!s}, "
            f"status_default_text_canonical={_status_default_text_canonical!s}, "
            f"status_emoji={_status_emoji!s}, "
            f"status_expiration={_status_expiration!s}, "
            f"status_text={_status_text!s}, "
            f"status_text_canonical={_status_text_canonical!s}, "
            f"team={_team!s}, "
            f"title={_title!s}, "
            f"updated={_updated!s}, "
            f"user_id={_user_id!s}, "
            f"username={_username!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
