"""slackwebapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from slackwebapi.api_helper import APIHelper
from slackwebapi.models.user_profile_object import (
    UserProfileObject,
)


class UsersProfileSetSchema(object):
    """Implementation of the 'users.profile.set schema' model.

    Schema for successful response from users.profile.set method

    Attributes:
        email_pending (str): The model property of type str.
        ok (str): The model property of type str.
        profile (UserProfileObject): The model property of type UserProfileObject.
        username (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ok": "ok",
        "profile": "profile",
        "username": "username",
        "email_pending": "email_pending",
    }

    _optionals = [
        "email_pending",
    ]

    def __init__(
        self,
        profile=None,
        username=None,
        email_pending=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a UsersProfileSetSchema instance."""
        # Initialize members of the class
        if email_pending is not APIHelper.SKIP:
            self.email_pending = email_pending
        self.ok = "True"
        self.profile = profile
        self.username = username

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        profile =\
            UserProfileObject.from_dictionary(
                dictionary.get("profile"))\
                if dictionary.get("profile") else None
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        email_pending =\
            dictionary.get("email_pending")\
            if dictionary.get("email_pending")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(profile,
                   username,
                   email_pending,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _email_pending=(
            self.email_pending
            if hasattr(self, "email_pending")
            else None
        )
        _ok=self.ok
        _profile=self.profile
        _username=self.username
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email_pending={_email_pending!r}, "
            f"ok={_ok!r}, "
            f"profile={_profile!r}, "
            f"username={_username!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _email_pending=(
            self.email_pending
            if hasattr(self, "email_pending")
            else None
        )
        _ok=self.ok
        _profile=self.profile
        _username=self.username
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email_pending={_email_pending!s}, "
            f"ok={_ok!s}, "
            f"profile={_profile!s}, "
            f"username={_username!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
